### ISSUE TITLE
Extra metadata does not support multi value keys

### ISSUE THREAD

**Issue by sebdah** [trentm/python-markdown2#120]
The current implementation of the extra `metadata` does not support documents with multi value keys, like:

```

---
layout: post
title: "Test post"
date: 2013-03-21 14:56
comments: true
categories:
- cat 1
- cat 2

---
This is regular
text
and should not be affected
```

Those documents are not covered at all and will be printed by Markdown2. I would expect this to return a `metadata` dict with lists, for example:

```
{'date': '2013-03-21 14:56', 'layout': 'post', 'categories': ['cat 1', 'cat 2'], 'comments': 'true', 'title': '"Test post"'}
```

**Comment by nicholasserra** [comment]
Fixed in #368
