### ISSUE TITLE
Disallow javascript: scheme in urls on safe mode

### ISSUE THREAD

**Issue by bluec0re** [trentm/python-markdown2#174]
allowing the javascript: scheme in urls makes the safe mode completely useless in terms of preventing XSS.

**Comment by alanhamlett** [comment]
Pretty big bug here, any plans to fix it? I can submit a PR based on #173?

**Comment by nicholasserra** [comment]
Sounds good @alanhamlett, PRs welcome :)

**Comment by bluec0re** [comment]
Are the other XSS issues (which I addressed in the PR 2 years ago) already fixed? (Didn't used the library anymore since the fixes weren't applied. I'm using RestructeredText now)

**Comment by alanhamlett** [comment]
@bluec0re it does now with the latest commit.

**Comment by nicholasserra** [comment]
Fixed in #230
