### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by 57even** [trentm/python-markdown2#176]
It is so great that a table of contents is implemented, but I can't figure out how to use it. I'm using markdown2 in Django with `context['markdown_text'] = markdown2.markdown(text, extras=["header-ids", "toc"])` but how can I access `toc_html`?

**Comment by devvynm** [comment]
Although I'm not the maintainer/developer, and I can't reference any official documentation to confirm my answer, after scanning and reading the source code I'm pretty confident you'd need to do something like this:

    markdown_html = markdown2.markdown(text, extras=["toc"])
    toc_html = markdown_html.toc_html

Where both markdown_html and toc_html each act as strings when treated like strings, but the unicode output from the markdown() or convert() methods has added attributes.

Additionally, the 'toc' extra implies the 'header-ids' extra, so you technically don't need to pass both to the constructor.

**Comment by nicholasserra** [comment]
Thanks for the answer ^
