### ISSUE TITLE
Markdown Breaks When HTML Used After Fenced Code Section

### ISSUE THREAD

**Issue by scovetta** [trentm/python-markdown2#188]
Sample Code:
https://gist.github.com/scovetta/72b2936222987820a4fe

When rendered on Github, renders as:

```
<div class="highlight highlight-python"><pre>test()</pre></div>

<p>foo <a href="http://quux.com">bar</a> baz</p>

<div>
</div>
```

When rendered using python-markdown2:

```
$ markdown2 --extras=fenced-code-blocks gist-example.md
<div class="codehilite"><pre><code><span class="n">test</span><span class="p">()</span>
</code></pre></div>



foo [bar](http://quux.com) baz

<div>
</div>
```

Note that the `bar` link doesn't get converted to HTML. This appears to be a problem when there is HTML (the div element) coming later in the document.

**Comment by chaudum** [comment]
I've experienced the same issue. However, putting the HTML into a single line solved the problem for now:

    ```json
    {
    ...
    }
    ```
    foo [bar](http://quux.com) baz
    <div class="youtube-wrapper"><iframe src="https://youtube.com/..."></iframe></div>

**Comment by yujiri8** [comment]
I have this same issue, and putting the HTML into a single line isn't viable for me because I need to have more fenced code blocks wrapped in HTML after the first one (I'm using the `markdown-in-html` extra, but not using that and putting the HTML-wrapped code block in literal HTML still messes up the stuff before it after the earlier fenced code blocks).

**Comment by ceteri** [comment]
This may be related to https://github.com/trentm/python-markdown2/issues/185 where `markdown-in-html` incorrectly parses HTML tags.

**Comment by Crozzers** [comment]
Hi all, ran through each of the cases in this issue and they all seem to be working against the master branch
