### ISSUE TITLE
how to process code block with "```"

### ISSUE THREAD

**Issue by weaming** [trentm/python-markdown2#196]
such as
    ```
    a
    b
    ```

**Comment by marios-zindilis** [comment]
This question makes no sense. Does the [wiki page for fenced-code-blocks](https://github.com/trentm/python-markdown2/wiki/fenced-code-blocks) help you? If not, please specify your problem in greater detail than just three words...

**Comment by weaming** [comment]
Yes, I mean the fenced code.

Now I'm using `misaka` module.
