### ISSUE TITLE
how convert <pre><code> tag ?

### ISSUE THREAD

**Issue by lioncui** [trentm/python-markdown2#198]
```
>>> from markdown import markdown
>>> a='''
...```
... test bash
... this is a test script!
...```
... '''
>>> 
>>> markdown(a)
u'<p><code>test bash\nthis is a test script!</code></p>'
>>>
```
it is \<p\>\<code\>, not \<pre\>\<code\>.

how?

**Comment by marios-zindilis** [comment]
Parsing of triple backticks is a feature of the "fenced-code-blocks" extra. If you want it, you can explicitly enable it like this:

    >>> markdown(a, extras=['fenced-code-blocks'])
    u'<pre><code>test bash\nthis is a test script\n</code></pre>\n'

Check out the [https://github.com/trentm/python-markdown2/wiki/Extras Wiki] for documentation on all Extras. Please close this issue if the answer was satisfactory.
