### ISSUE TITLE
How to enable python-markdown2 with function like Github comment textbox

### ISSUE THREAD

**Issue by extremewaysback** [trentm/python-markdown2#199]
How to get the functions like Github comment box in <font color='red'>python-markdown2</font>:

Function:

Can drag image directly into the comment box

![screen shot 2016-01-14 at 4 36 49 pm](https://cloud.githubusercontent.com/assets/13831728/12319388/1509aa4e-badd-11e5-99db-0d5c7241a98e.png)

**Comment by marios-zindilis** [comment]
That has nothing to do with python-markdown2. All that python-markdown2 is convert markdown to HTML. 

You can achieve what you want with a combination of javascript and some backend work. Take a look at [http://www.dropzonejs.com/ Dropzone] for an example in the javascript side.

Please close this issue, it is irrelevant to python-markdown2.

**Comment by extremewaysback** [comment]
@marios-zindilis Thanks!
