### ISSUE TITLE
No highlight for inline code blocks

### ISSUE THREAD

**Issue by riteme** [trentm/python-markdown2#200]
python-markdown2 is very nice and I used it in my blog.  
But it seems that markdown2 will process all code blocks to be highlighted.
```markdown
'inline-code`和`Hello, world`
```
![](http://7xq4ng.com1.z0.glb.clouddn.com/python-markdown2-inline-1.png)

It has been parsed to these:
![](http://7xq4ng.com1.z0.glb.clouddn.com/python-markdown2-inline-2.png)

Is there any way to disable it for inline code?
Thank you.

**Comment by marios-zindilis** [comment]
It's not clear what the problem is here. Can you please provide a longer example of your code that demonstrates the issue, so that we can reproduce it? 

For example something similar to this:
```
>>> from markdown2 import markdown
>>> markdown("'inline-code`?`Hello, world`")
u"<p>'inline-code<code>?</code>Hello, world`</p>\n"
```

**Comment by riteme** [comment]
Sorry, I found that it was caused by strapdown. Python-markdown2 works correctly. ;)
