### ISSUE TITLE
Support for CLI css / inline style

### ISSUE THREAD

**Issue by GuidoS** [trentm/python-markdown2#206]
Would it be possible to add css elements inline or as relative path into the CLI?

For example:

markdown2 -x style https://raw.githubusercontent.com/markdowncss/air/master/index.css readme.md > readme.html

**Comment by DoWhileGeek** [comment]
I second this, the output looks rather ugly by default.

**Comment by DoWhileGeek** [comment]
@GuidoS Since this library just outputs html snippets, try dumping the output into a jinja2 template with css markup.

**Comment by GuidoS** [comment]
I am closing this issue.
