### ISSUE TITLE
Potential Extension

### ISSUE THREAD

**Issue by ewankirk** [trentm/python-markdown2#219]
I've been using markdown2 a lot in a recent project to convert a \LaTeX document generator into an online research environment.  Combined with MathJax, Markdown2 with the footnotes extension is  pretty much perfect.  However, the one thing that Markdown can't do is number figures and tables.  This is pretty much essential in research papers and is also a useful feature in other styles of documentation.  

Whilst I understand that there are way too many "standards" for Markdown, I wanted to add an extension to handle figure, table and equation numbering to Markdown.  What I've done (in a relatively few lines of code) is add a preprocessor which generates generic "counters" which can be used to number equations.  The syntax is as follows.

When you first want to label an item (figure, table, image whatever), you add a markdown item 

```
     [#counter_id](:item_tag)
```

and when you want to refer to it in the text you use `[:item_tag]`.  Here both `counter_id` and `item_tag` are "words" in the regex sense.

During conversion, the first pass identifies all the labels and creates counters as required and increments them if they're already created.  During the second pass, the counter integers are replaced in the text.  In principle, each counter can have it's own css style associated with it.  At present it doesn't hyperlink the references to the original item but that would be easy to add.

The code is about 40 lines of Python.

So the issue is: Is this more generally useful?  There's almost no support for "exhibit numbering" in any Markdown converters -- which is why I had to write my own.  I could certainly add this as an "extra" in markdown2 if there was general support for it but I don't want to add useless cruft to a project.  Comments?

**Comment by nicholasserra** [comment]
Hello, thanks for the information :) I think this would be cool to have as an extra, as long as the code is generally self contained or doesn't complicate any of the main methods too much. I'd say open a PR and we'll see where it goes. Thank you

**Comment by ewankirk** [comment]
Ok, I'll do the Pull Request and see how it goes. After looking at the master code, I'll probably change the "numbering" Markdown syntax a little bit to make collisions with existing Markdown impossible. Thanks.

**Comment by ewankirk** [comment]
After some thought about the syntax, I've changed it to be more flexible.  A definition of a figure, table, equation etc is

```
   [#CounterId optional pre_text @refid optional_pos_text]
```
If `CounterId` isn't defined then `refid` is set to be 1.  Otherwise it is the next value of `CounterId`.  The HTML which is output is
```html
    <figcaption class="CounterId' id="counter-ref-refid`>
    optional pre text counter_val optional post text
    </figcaption>
```

So, for example
```
    [#tablecounter Table @mytable: some interesting stuff]
```
will output
```html
   <figcaption class="tablecounter" id="counter-ref-mytable">Table 1: some 
    intesting stuff</figcaption>
```
assuming that this is the first reference to `tablecounter` in the document.

When you wish to refer to the table you use a link of the form
```
    [@refid]
```
which outputs the html
```html
   <a href="#counter-ref-refid" class="CounterId">counter_val</a>
```
So in the example above, markdown like this
```
    In Table [@mytable] we see something interesting
```
will output
```html
    In Table <a href="#counter-ref-mytable" class="tablecounter">1</a> we 
    see something interesting
```

Different counters can have different styles by using CSS selectors
```css
     a.tablecounter: {color: green}
     figcaption.tablecounter: {font-size: smaller}
```
for example.

**Comment by ewankirk** [comment]
Is there anything more you need from me before merging this into the main branch and releasing?  Do you need the Wiki entry now?

**Comment by nicholasserra** [comment]
Do you mean in reference to PR #220? That has been merged. Wiki entry would be good. We probably need to get a new release out @trentm

**Comment by ewankirk** [comment]
Ok, I'll get on the wiki entry now.

**Comment by ewankirk** [comment]
Ok, done.

**Comment by davidlowryduda** [comment]
I recommend closing this issue now, as it seems to be complete.

**Comment by nicholasserra** [comment]
Good look, thanks

**Comment by ewankirk** [comment]
That’s great.  Thanks.
