### ISSUE TITLE
how to display line number in a code block?

### ISSUE THREAD

**Issue by seniorcandy** [trentm/python-markdown2#225]

**Comment by keysona** [comment]
Sorry, this lib can not do this.
It's just convert markdown to html.

And line number may be use css or js?

**Comment by davidlowryduda** [comment]
Line numbers in code blocks can be done using css. See https://codepen.io/elomatreb/pen/hbgxp or https://www.sylvaindurand.org/using-css-to-add-line-numbering/ for two examples (although they are essentially the same) of implementations.

**Comment by seniorcandy** [comment]
@davidlowryduda 
Thanks man, it looks pretty good, but when I try to select the code in multiple lines, the numbers are also selected, and when I copy and paste the code, every empty line become two empty lines.
They look like 

```
def print_hi(name)

	puts "Hi, #{name}"

end


print_hi('Tom')

#=> prints 'Hi, Tom' to STDOUT.
```

**Comment by davidlowryduda** [comment]
@seniorcandy 
Perhaps it would help to give you a single, self-contained example. So I made a self-contained example [on my side website](http://david.lowryduda.com/linenumberingwithcss.html). Perhaps it makes more sense now?

**Comment by seniorcandy** [comment]
@davidlowryduda 
Yeah, it really helps a lot.
Much appreciated

**Comment by nicholasserra** [comment]
Thanks @davidlowryduda . I'm gonna close this now.
