### ISSUE TITLE
Auto detect URLs and add links

### ISSUE THREAD

**Issue by jakirkham** [trentm/python-markdown2#226]
Something that would be nice is if URLs like ( `https://google.com` ) were automatically rendered as a link like ( https://google.com ).

**Comment by nicholasserra** [comment]
I thought we had an extra for that. Maybe not. Pull requests welcome, thanks :)

**Comment by remram44** [comment]
There is an extra, it's documented over there: https://github.com/trentm/python-markdown2/wiki/link-patterns

It really doesn't work though, as it breaks the `[text](address)` construct.

**Comment by remram44** [comment]
Here is the problem, using the link pattern listed on the [wiki page](https://github.com/trentm/python-markdown2/wiki/link-patterns):

```python
>>> link_patterns = [(re.compile(r'((([A-Za-z]{3,9}:(?:\/\/)?)(?:[\-;:&=\+\$,\w]+@)?[A-Za-z0-9\.\-]+(:[0-9]+)?|(?:www\.|[\-;:&=\+\$,\w]+@)[A-Za-z0-9\.\-]+)((?:\/[\+~%\/\.\w\-_]*)?\??(?:[\-\+=&;%@\.\w_]*)#?(?:[\.\!\/\\\w]*))?)'),r'\1')]
>>> m = markdown2.Markdown(extras=['link-patterns'], link_patterns=link_patterns)
>>> m.convert('''link: https://gitter.remram.fr/''')
u'<p>link: <a href="https://gitter.remram.fr/">https://gitter.remram.fr/</a></p>\n'
>>> m.convert('''other [link](https://gitter.remram.fr/)''')
u'<p>other <a href="<a href="https://gitter.remram.fr/">https://gitter.remram.fr/</a>">link</a></p>\n'
```

Notice `<a href="<a`...

**Comment by Scimonster** [comment]
If i use a much simpler link parsing regex, i can make standard `[text](link)` syntax work:

```python
In [56]: link_patterns = [(re.compile(r'(?<!=")(https?:\/\/.+)(?!")'), r'\1')] 

In [57]:  m = markdown2.Markdown(extras=['link-patterns'], link_patterns=link_patterns)

In [58]: m.convert('''link: https://gitter.remram.fr/''')
Out[58]: u'<p>link: <a href="https://gitter.remram.fr/">https://gitter.remram.fr/</a></p>\n'

In [59]: m.convert('''other [link](https://gitter.remram.fr/)''')
Out[59]: u'<p>other <a href="https://gitter.remram.fr/">link</a></p>\n'

In [60]: m.convert('''(from https://gitter.remram.fr/)''')
Out[60]: u'<p>(from <a href="https://gitter.remram.fr/)">https://gitter.remram.fr/)</a></p>\n'
```

However, this has false positives (including the parentheses in the last example) and false negatives (no ftp:// links or other protocols), so weigh your needs before picking it.
