### ISSUE TITLE
2.3.2 regression: fully-qualified links are urlencoded

### ISSUE THREAD

**Issue by lopopolo** [trentm/python-markdown2#233]
I think this is caused by GH-230.

Sample markdown code:

```markdown
[GitHub](https://github.com/lopopolo)
```

Under 2.3.1 with safe_mode = escape renders the following link:

```html
<a href="https://github.com/lopopolo">GitHub</a>
```

Under 2.3.2 with safe_mode = escape renders the following link:

```html
<a href="https%3A%2F%2Fgithub.com%2Flopopolo">GitHub</a>
```

**Comment by nicholasserra** [comment]
Thanks for the report. Not sure how tests didn't catch this.

**Comment by lopopolo** [comment]
Because the tests enforce this behavior:

https://github.com/trentm/python-markdown2/pull/230/files#diff-2975f6a2bb599e9479d075d841dbdbccR11

There are also no safe mode happy path tests (i.e.: ensuring a valid link with nothing needing to be escaped turns into a valid link)

**Comment by nicholasserra** [comment]
Fixed in #236

**Comment by stefanw** [comment]
Thanks for the fix! Because of the regression, please consider releasing 2.3.3.

**Comment by nicholasserra** [comment]
2.3.3 released
