### ISSUE TITLE
Support for strikethrough

### ISSUE THREAD

**Issue by iShawnWang** [trentm/python-markdown2#242]
`~~xxx~~` => ~~xxx~~ is needed for declare something that is finished with markdown, I am surprised that python-markdown2 don't support this syntax

I am looking forward to this new feature ~
# 😄

**Comment by kluchrj** [comment]
I was thinking of writing a patch for this, however it looks like it's already implemented as an extra, just undocumented. See this commit: https://github.com/trentm/python-markdown2/commit/ed7208da1bfc8f26b7a6129ec13429d9359bdc26

**Comment by nicholasserra** [comment]
Nice, thanks @kluchrj

**Comment by chichur** [comment]
```
>>> from markdown2 import Markdown
>>> markdowner = Markdown()
>>> markdowner.convert("*boo!*")
>>> '<p><em>boo!</em></p>\n'
>>> markdowner.convert("~~boo!~~")
>>> '<p>~~boo!~~</p>\n'
```
What's wrong?

**Comment by chichur** [comment]
Sorry it's extras
```
>>> import markdown2
>>> markdown2.markdown("~~boo!~~", extras=["strike"])
'<p><strike>boo!</strike></p>\n'
```

**Comment by codebykat** [comment]
I just added this to the wiki page as well! https://github.com/trentm/python-markdown2/wiki/Extras

**Comment by yifeikong** [comment]
I'm searching for `delete line` and can not find any info, I have to search `strike through` to find the correct answer. I mention `delete line` here, in case some other non-native English speakers are searching for the same problem.
