### ISSUE TITLE
Footnote titles not translatable

### ISSUE THREAD

**Issue by Flimm** [trentm/python-markdown2#244]
The `footnotes` extension generates HTML code like this:

```
<a href="#fnref-%s" class="footnoteBackLink" title="Jump back to footnote %d in the text.">&#8617;</a>
```

The string "Jump back to footnote %d in the text" is not translatable or customisable. Neither is the U+21A9 character ↩, which isn't ideal in some languages that aren't left-to-right.

**Comment by davidlowryduda** [comment]
I wonder: to what extent is this worth adding? Adding in many languages would do little besides add bloat, unless these languages had a known use-case.

Is there a particular language that you had in mind?

**Comment by Flimm** [comment]
I do. I can see why we might not want to include translations for just a couple of strings in this package. Instead, I propose that there be an easy way to customise the translatable strings. For example, something like:

```python
html = markdown2(markdown, extras=['footnotes'], extras_config={
    'footnotes': {
        'footnote_title': 'Retournez vers footnote %d',
        'footnote_link_text': '↩',
    },
})
```

Or maybe something prettier with the `Markdown` class.

```python
m = Markdown()
m.footnote_title = 'Retournez vers footnote %d'
m.footnote_link_text = '↩'
```
