### ISSUE TITLE
Can't wrap `code` in [link]()

### ISSUE THREAD

**Issue by TheInitializer** [trentm/python-markdown2#259]
If I do
```
[`example`](https://google.com)
```
the expected output is
```
<a href="https://google.com"><code>example</code></a>
```
[`example`](https://google.com)

However, the `<code>` tags are escaped:
```
<a href="https://google.com">&lt;code&gt;example&lt;/code&gt;</a>
```
[\<code\>example\</code\>](https://google.com)

**Comment by nicholasserra** [comment]
Thanks for the report! PRs welcome. Seems like an edge case.

**Comment by serpulga** [comment]
+1

**Comment by serpulga** [comment]
```
----------------------------------------------------------------------
Ran 132 tests in 0.209s

FAILED (4 failures)
make: *** [test] Error 4
```

**Comment by malcolmr** [comment]
Note that this regressed between 2.3.1 and 2.3.2.

Bisection says this was due to 000343d (possibly because of the additional call to `_xml_escape_attr()` in `_do_links()`?

**Comment by CNG** [comment]
Ah, glad to have found this. Maybe it's an edge case for others, but I find I use this pattern in almost every technical document I write since I like to link functions, variables, etc., that also use monospace font per style conventions.
