### ISSUE TITLE
Search for items only within metadata header

### ISSUE THREAD

**Issue by mdhowle** [trentm/python-markdown2#261]
When parsing the metadata key-value pairs, it incorrectly searches the entire text instead of the metadata header.
For example, 

```python
content = """---
Foo: bar
---

This is a test:
"""
md = markdown2.Markdown(extras=['metadata'])
md.convert(content)
print(md.metadata)
```

results in  `{'Foo': 'bar', 'test': ''}` while it should return only `{'Foo': 'bar'}`

I have submitted a PR for a fix #260

**Comment by nicholasserra** [comment]
Fixed in #260
