### ISSUE TITLE
hypertext link in list

### ISSUE THREAD

**Issue by aurely06** [trentm/python-markdown2#273]
Hi, 

The hypertext link inside a list doesn't work for me. For example I have a list with this item in my .ipynb   `       * [toto](#toto)\n"` 
and json side I have :
`<li><a href=\"#toto\">Toto</a></li>`
`<h2>toto</h2>`

So, I think that json side should be : 
`<li><a href=\"#toto\">Toto</a></li>`
`<div id="toto"><h2>toto</h2></div>`

Please tell me if I'm wrong ;)
thanks

**Comment by aurely06** [comment]
Indeed, it seems to be ok with a basic test. I will investigate that :)
Thanks!

**Comment by aurely06** [comment]
I think that the issue is Zeppelin side. Have you ever used internal link inside a zeppelin notebook ?

**Comment by nicholasserra** [comment]
Nope, i'm unfamiliar with Zeppelin :-/

Thanks for investigating further. If you find the issue is not related to this package please hit close :)

**Comment by aurely06** [comment]
Yes I close the issue, is not related to your package. Thank you ;)
