### ISSUE TITLE
Code fences inside of lists exits list

### ISSUE THREAD

**Issue by albertyw** [trentm/python-markdown2#276]
Possibly related to #275 or #263 

Adding a code block inside of a list results in the parser immediately exiting the list `<li>` and `<ul>` / `<ol>` for the code block and anything below it.  Note that this is with "fenced-code-blocks" enabled.

For this markdown:
```
1. asdf
    ```
    asdf
    ```
    asdf
1. qwer
```

------------
python-markdown2 produces:
1. asdf
```
asdf
```
asdf
1. qwer

-----------
Github markdown syntax produces:
1. asdf
    ```
    asdf
    ```
    asdf
1. qwer

**Comment by momja** [comment]
@trentm this issue can be resolved
