### ISSUE TITLE
TOC depth

### ISSUE THREAD

**Issue by MattX** [trentm/python-markdown2#277]
I'd be interested in having a way to set the TOC depth (i.e. maximum header level that will be added to the TOC). I could write a pull request, I'm just not completely sure how that depth parameter would be passed.

It looks like the `header-ids` extra accepts a prefix as an argument through the `extras` dictionary, would doing the same with `toc` be OK?

**Comment by nicholasserra** [comment]
So the `extras` input can be a list or a dictionary. If it's a dictionary, you can add extra data via the extra key name. A good example is the `html-classes` extra. Check out the format in this test options file: https://github.com/trentm/python-markdown2/blob/master/test/tm-cases/html_classes.opts

For example: `markdowner = Markdown(..., extras={"html-classes": {"more-data": "here"})`

Hopefully that gets you going, let me know if you have any other questions, thanks :)
