### ISSUE TITLE
Link Pattern Regex for finding hashes produces odd output

### ISSUE THREAD

**Issue by blitzmann** [trentm/python-markdown2#287]
I have a few link patterns to help parse GitHub-specific markdown, specifically to link usernames, issues, and commits. This is what I have so far:

```
import markdown2
import re

link_patterns = [
    (re.compile("#(\d+)", re.I), r"https://github.com/pyfa-org/Pyfa/issues/\1"),
    (re.compile("@(\w+)", re.I), r"https://github.com/\1"),
    (re.compile("([0-9a-f]{6,40})", re.I), r"https://github.com/pyfa-org/Pyfa/commit/\1")
]

markdowner = markdown2.Markdown(
    extras=['link-patterns'],
    link_patterns=link_patterns)

print(markdowner.convert("this is a test issue #1234 with a test commit (addeddd) made by test @username more text"))
```

This worked well until I added that third pattern to look for any hash and convert it to a link to the commit. That code produces the following:

```
<p>this is a test issue md5-<a href="https://github.com/pyfa-org/Pyfa/commit/6828e8bf5a824ad95dd94fa403b7cce8">6828e8bf5a824ad95dd94fa403b7cce8</a> with a test commit (<a href="https://github.com/pyfa-org/Pyfa/commit/addeddd">addeddd</a>) made by test md5-<a href="https://github.com/pyfa-org/Pyfa/commit/52df4a7c6713b26289e286360c4b1a6f">52df4a7c6713b26289e286360c4b1a6f</a> more text</p>

```

Note the `md5-` and then a link to the md5 hash. I'm sure this is picking up some sort of processing markdown2 is doing internally. If I make that third pattern the first one, it produces the correct output:

```
link_patterns = [
    (re.compile("([0-9a-f]{6,40})", re.I), r"https://github.com/pyfa-org/Pyfa/commit/\1"),
    (re.compile("#(\d+)", re.I), r"https://github.com/pyfa-org/Pyfa/issues/\1"),
    (re.compile("@(\w+)", re.I), r"https://github.com/\1"),
]
```

```
<p>this is a test issue <a href="https://github.com/pyfa-org/Pyfa/issues/1234">#1234</a> with a test commit (<a href="https://github.com/pyfa-org/Pyfa/commit/addeddd">addeddd</a>) made by test <a href="https://github.com/username">@username</a> more text</p>
```

I would be interested in knowing why exactly the first try didn't work well. Even if it's an implementation detail that can't really be fixed. I hope this issue can also provide some insight to anyone else trying to work with hashes and getting some wonky output - simply use it as the first pattern. :)

**Comment by nicholasserra** [comment]
Those `md5` outputs are used internally when substituting text, you can see it in the markdown.py file if you search. If they're appearing in the final output of the convert, then there's a bug in the code somewhere that's leaking them.

**Comment by blitzmann** [comment]
Thanks for the info. It's possible that the pattern operations aren't "finalized" and the `md5-` bits aren't scrubbed before the next pattern is applied. Knowing nothing about the underlying code, might be easy enough to finalize the text after each pattern application.

**Comment by blitzmann** [comment]
This seems to be a more serious issue if you're looking to make links from hashes (with `(re.compile("([0-9a-f]{6,40})", re.I), r"https://github.com/pyfa-org/Pyfa/commit/\1")`)

Even if I have the following code, it breaks:

```
import markdown2
import re

link_patterns = [
    (re.compile("([0-9a-f]{6,40})", re.I), r"https://github.com/pyfa-org/Pyfa/commit/\1")
]

markdowner = markdown2.Markdown(
    extras=['link-patterns'],
    link_patterns=link_patterns)

print(markdowner.convert("This is inline `code` text"))
```

This breaks and produces this output:
`<p>This is inline <code>md5-<a href="https://github.com/pyfa-org/Pyfa/commit/a20b4428dd1d7b801be07237cfdd977b">a20b4428dd1d7b801be07237cfdd977b</a></code> text</p>`

So it looks like this is a fundamental issue with the way `markdown2` tags things that are changing with hashes. My link pattern will find anything that markdown2 has touched and muck it up.

As a work around, it would seem like I can create two instances of `markdown2` and process the text first without the hash links, and then again with the hash links. That way, the hash links are only processed on already-processed text:

```
import markdown2
import re

link_patterns = [
    (re.compile("([0-9a-f]{6,40})", re.I), r"https://github.com/pyfa-org/Pyfa/commit/\1")
]

markdowner = markdown2.Markdown()

text = markdowner.convert("This is inline `code` text")

markdowner = markdown2.Markdown(
    extras=['link-patterns'],
    link_patterns=link_patterns)

text = markdowner.convert(text)

print(text)
```

**HOWEVER**, it doesn't seem to work all that well when I use a more complex example:
```
import markdown2
import re

link_patterns = [
    (re.compile("#(\d+)", re.I), r"https://github.com/pyfa-org/Pyfa/issues/\1"),
    (re.compile("@(\w+)", re.I), r"https://github.com/\1")
]

markdowner = markdown2.Markdown(
    extras=['link-patterns'],
    link_patterns=link_patterns)

text = markdowner.convert("this is a test issue #1234 with a test commit (addeddd) made by test @username more text")

link_patterns = [
    (re.compile("([0-9a-f]{6,40})", re.I), r"https://github.com/pyfa-org/Pyfa/commit/\1")
]

markdowner = markdown2.Markdown(
    extras=['link-patterns'],
    link_patterns=link_patterns)

text = markdowner.convert(text)

print (text)```

I think this is because `markdown2` automatically encases the text in a `<p>` tag, and ignores everything within that tag? if I do something like `text = markdowner.convert('test here' + text)` is seems to work because the first few characters aren't a tag... ?

Seems really janky

**Comment by Crozzers** [comment]
So my understanding of the issue is that the way markdown2 tags special text is by using plain text strings like `md5-[hash]`, which clashes a lot with real-world use. The easiest way I can think of to fix this is changing what markdown2 uses to "tag" text.

Perhaps, instead of using plain text `md5-[hash]`, we could use a number based tagging system wrapped in special unicode characters since the chance of special unicode chars clashing with a regular expression I think are low. From my testing, using a tagging format like `\u0002%d\u0003` in the `_do_link_patterns` function works for the original test case mentioned in this issue.

I don't think this would work globally but for the link-patterns extra it seems promising.
cc @nicholasserra thoughts?
