### ISSUE TITLE
how can i make two bullets ??

### ISSUE THREAD

**Issue by LoveCodingg** [trentm/python-markdown2#289]

**Comment by nicholasserra** [comment]
Can you be more specific?

**Comment by LoveCodingg** [comment]
(I have this code for bullet , how can i repeated it to make two bullets ?)

 # Player's Bullet Setup

    
    bullet = turtle.Turtle()
    bullet.color("Yellow")
    bullet.shape("triangle")
    
    bullet.penup()
    bullet.speed(0)
    bullet.setheading(90)
    bullet.shapesize(0.5, 0.5)
    bullet.setposition(0, -250)
    bullet.hideturtle()

    bullet_speed = 50

**Comment by nicholasserra** [comment]
Does this have anything to do with this markdown library?

**Comment by LoveCodingg** [comment]
i don't understand
