### ISSUE TITLE
Does --extras options toc support chinese characters？

### ISSUE THREAD

**Issue by onewesong** [trentm/python-markdown2#316]
![image](https://user-images.githubusercontent.com/17920822/49732721-77deb200-fcba-11e8-85f6-86e1c589b29d.png)

**Comment by nicholasserra** [comment]
Hm, good question. I'd assume it does. Do you have the input text from this so I can run some tests?

**Comment by StoneMoe** [comment]
> Hm, good question. I'd assume it does. Do you have the input text from this so I can run some tests?

用于测试的字符串

**Comment by nicholasserra** [comment]
Running that text through the TOC extra had no issues for me. If a failing test can be written we can reopen this. Thanks!
