### ISSUE TITLE
Please do not set an alias for (i.e. overwrite) build

### ISSUE THREAD

**Issue by thmo** [trentm/python-markdown2#323]
https://github.com/trentm/python-markdown2/blob/a3c378d7b88de9163462b126faeac0f93cf077ef/setup.cfg#L2

In the Fedora spec I have to patch this out, as the build environment expects `setup.py build` to work in an "expected" way (for example to accept the `-e` option).

**Comment by nicholasserra** [comment]
Hello. I'm curious what you're doing that you're having to do a `build` on the codebase? Are you not pulling from pypi and instead building on your own?

This change came in to add wheel support. I'm not too well versed on the package build stuff. But I expect I can just remove this alias and hack it into our release script for the pypi upload here

https://github.com/trentm/python-markdown2/blob/master/tools/cutarelease.py#L180

Sorry for the delay on this. Just need to figure out the alternative.

**Comment by thmo** [comment]
Well, it's just the standard way of doing things for Fedora (Python) packages: There, packages are always "build" from source, Fedora is not relying on wheels or other "binary" packages.

I mean, if you have a script to cut a release anyway, you could change it to call `sdist` and `bdist_wheel` instead of relying on the alias?

**Comment by nicholasserra** [comment]
Yeah that's what i'm thinking i'll do
