### ISSUE TITLE
consecutive blockquotes shouldn't be merged

### ISSUE THREAD

**Issue by de-code** [trentm/python-markdown2#332]
It seems consecutive quotes (separated by two line feeds) are merged if there isn't any other text in between.

e.g.:

```python
from markdown2 import markdown
print(markdown('> quote 1\n\n> quote 2'))
```

outputs:

```xml
<blockquote>
  <p>quote 1</p>
  
  <p>quote 2</p>
</blockquote>
```

expected something like:

```xml
<blockquote>
  <p>quote 1</p>
</blockquote>

<blockquote>
  <p>quote 2</p>
</blockquote>
```

Adding non-quoted text in-between results in separate blockquotes as expected:

```python
print(markdown('> quote 1\n\nno quote\n> quote 2'))
```

```xml
<blockquote>
  <p>quote 1</p>
</blockquote>

<p>no quote</p>

<blockquote>
  <p>quote 2</p>
</blockquote>
```

Replacing `no quote` in the above code with a whitespace removes that separation again.

The same seems to be true for `python-Markdown`.

In GitHub renders markdown as expected:

> quote 1

> quote 2

**Comment by nicholasserra** [comment]
Fixed in #356
