### ISSUE TITLE
Pygment 2.5.1 is breaking test cases

### ISSUE THREAD

**Issue by ryanvilbrandt** [trentm/python-markdown2#338]
Pygments updated to 2.5.1 early on the 26th. This is breaking some of the unit tests.

I'll make a PR to fix it soon.

**Comment by nicholasserra** [comment]
Fixed in https://github.com/trentm/python-markdown2/commit/55ba78e29ac983978806970ce4b81718fe68275b

I cherry picked your commit. Thanks!
