### ISSUE TITLE
backticks don't work inside links

### ISSUE THREAD

**Issue by yujiri8** [trentm/python-markdown2#344]
Test case:
```
[`stuff`](https://example.com)
```
Expected output:
```
<a href="https://example.com"><code>stuff</code></a>
```
Actual output:
```
<a href="https://example.com">&lt;code&gt;stuff&lt;/code&gt;</a>
```
For the time being, I'm getting around this by writing my links directly in HTML when the anchor text contains code.

Note: the Daring Fireball implementation doesn't have this behavior; it gives the output I expected.

**Comment by nicholasserra** [comment]
Fixed in #449
