### ISSUE TITLE
Pre Element implemented badly

### ISSUE THREAD

**Issue by George3d6** [trentm/python-markdown2#347]
Currently converting a pre element from markdown to HTML doesn't work

The following:
```
/```
# This is a comment
/```
```
(Without the `/`s, added those because I'm not sure how to get javascritp to render the triple code quotes otherwise)
Will be rendered as though `#` is a title tag, in spite of it being inside a `<pre>` tag.

**Comment by yujiri8** [comment]
This doesn't happen to me as long as the fenced-code-blocks extra is on, on the latest version (2.3.8).

**Comment by George3d6** [comment]
Ok, did not notice `fenced-code-blocks` extra flag.
