### ISSUE TITLE
How to add `srcset` and `sizes` attribute to img ?

### ISSUE THREAD

**Issue by dsin** [trentm/python-markdown2#354]
Hi, 

Is there any way to add an `srcset` and `sizes` attribute to image tag ?

**Comment by nicholasserra** [comment]
No, sorry, this isn't currently supported.

**Comment by dsin** [comment]
@nicholasserra Is there any workaround I can do ?

**Comment by nicholasserra** [comment]
I'd probably parse image tags with regex and replace them.
