### ISSUE TITLE
No underline support?

### ISSUE THREAD

**Issue by starry69** [trentm/python-markdown2#359]
Hi I was looking for "u" or "ins" support for underline text I've looked docs and codes and I couldn't find it anywhere, so can we hope for this being added soon? Or link me if it's already available.. thanks

**Comment by nicholasserra** [comment]
Correct, looks like this package does not support it. PRs welcome, thanks!

**Comment by starry69** [comment]
> Correct, looks like this package does not support it. PRs welcome, thanks!

Hi i just made a pr to add this, looking forward :)
