### ISSUE TITLE
latex support ?

### ISSUE THREAD

**Issue by Mike-HubGit** [trentm/python-markdown2#366]
Don't know if it is an issue or a pull request or not 'in line' with the markdown2 library ;-)

in the frame of JupyterLab, latex expressions can be added inside Markdown. I understand this is not rigourous Markdown but perhaps with the extras it could be handled better. A simple example : 
```
**some text**
$a_1=b_3$

$$R_1^2/R_4$$
```

due to the "underscore" use of LaTex for indices, the default markdown engine crashes the latex formula (it makes italic style).
perhaps a new extra mode that does not parse anything inside '$' or '$$' would be great ?
At this time, I solved it with the extra 'code-friendly' but this is indirect.

Thanks a lot for this library.

**Comment by nicholasserra** [comment]
Any issue with just putting it inside of a fenced code block, like you did on the PR description?

**Comment by Mike-HubGit** [comment]
The aim is not to display latex code but to allow latex code rendering by JupyterLab. In a fenced block, it will be considered as code and not rendered.
I join a sample screenshot of something generated with markdown2 in the contexte of JupyterLab : as you can see, I display Matrixes in the table. This is possible because JupyterLab allows renders Latex through MathJax when detecting $$...$$ or $..$ expressions, inside Markdown syntax.

<img width="779" alt="Capture d’écran 2020-08-11 à 07 03 16" src="https://user-images.githubusercontent.com/65092924/89859223-d0a5d280-dba0-11ea-9bac-3b02de21a9fd.png">
