### ISSUE TITLE
break-on-newline not mentioned in code.

### ISSUE THREAD

**Issue by aminancelot** [trentm/python-markdown2#367]
https://github.com/trentm/python-markdown2/blob/master/lib/markdown2.py#L43 doesn't mention break-on-newline but https://github.com/trentm/python-markdown2/wiki/Extras does.

Is there some grey area? experimental or something? Works fine for me.

**Comment by nicholasserra** [comment]
Grey area. Just diverging docs is all. Wouldn't be surprised if there were others missing. Thanks! Fixed via commit.
