### ISSUE TITLE
Backslashes removed by adjacent backticks

### ISSUE THREAD

**Issue by alexpeattie** [trentm/python-markdown2#369]
I've stumbled across some odd behaviour where backslashes are removed by adding backticks elsewhere in the converted Markdown - but only if the phrase inside the backticks is a prefix of the word following the backslash. It's probably easiest to show with an example:

```python
import markdown2

>>> markdown2.markdown('hello \world!')
'<p>hello \\world!</p>\n'

>>> markdown2.markdown('hello \world! My favourite letter is `w`.')
'<p>hello world! My favourite letter is <code>w</code>.</p>\n'

>>> markdown2.markdown('hello \world! My favourite letter is `x`.')
'<p>hello \\world! My favourite letter is <code>x</code>.</p>\n'
```

I'm happy to try my hand at PRing a fix, but I might need some pointers (if anyone has any idea) of where this behaviour might be coming from 🤔 ?

**Comment by nicholasserra** [comment]
That's an interesting one. Not sure where they might be coming in. Thanks for the report!
