### ISSUE TITLE
Choice of language class for fenced code blocks with the highlightjs-lang extension

### ISSUE THREAD

**Issue by dkasak** [trentm/python-markdown2#370]
Currently, if the `highlightjs-lang` extension is enabled, the language of the fenced code block will be added as a HTML class to the code element. E.g. for Python code blocks, a `python` class will be added to the block.

However, a more common and interoperable technique is to prepend the language name with `language-`, e.g. `language-python`. This is mentioned in the [WHATWG HTML standard](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-code-element) and is expected by a variety of other tools and clients (an example being the [Element Matrix client](https://github.com/vector-im/element-web)). I personally encountered this issue while trying to use [urlwatch](https://github.com/thp/urlwatch) (which depends on python-markdown2) to send Markdown reports to Matrix.

Would you consider changing this or adding a configuration option for it?

**Comment by nicholasserra** [comment]
Seems sane. Any issues if we kept both? aka `class="python language-python"` to support this new standard and also in case anyone is depending on the old way? I'm going to peek the current tests to see if this is even checked.

**Comment by nicholasserra** [comment]
In current tests it seems whoever implemented it just assumed the input text would include the `language-` string, as opposed to prepending it in the code.

https://github.com/trentm/python-markdown2/blob/master/test/tm-cases/highlightjs_lang.text#L5-L11

**Comment by dkasak** [comment]
> In current tests it seems whoever implemented it just assumed the input text would include the `language-` string, as opposed to prepending it in the code.

That's not a very common usage, in my experience. Usually you'd only write the language name there, as in the first example.

> Any issues if we kept both?

None that I see. I tested it in a few places and it works great. I think this would probably be the best way forward since it keeps compatibility and also enables the more standard behaviour.
