### ISSUE TITLE
is there a module for apache or for another web server to transform md files in html on the fly?

### ISSUE THREAD

**Issue by ecxod** [trentm/python-markdown2#375]
okay I could make such a thing wit a rewrite rule but I thought that prolly there is a more elegant solution with a web server module.
Do you know about such a think ?

**Comment by nicholasserra** [comment]
Not sure I understand. What do you want to do exactly?

**Comment by ecxod** [comment]
I am searching a apache (or some other web server) module that automatically transforms MD code in html.
right now I do this with a rewrite rule in htaccess but I thought it would be more funny to directly do this in a browser module.
if you supply a *.md or a md shebang file it should automatically rewrite it in html.

**Comment by nicholasserra** [comment]
Sounds like backend server functionality that would live closer to your application logic as opposed to apache or nginx. For example, in your application framework code, not in your server configs.
