### ISSUE TITLE
[Feature request] Add possibility for target="_blank" on href's

### ISSUE THREAD

**Issue by JeffAbrahamson** [trentm/python-markdown2#383]
As far as I can tell from the docs and scanning the code, this isn't present.  It would be nice to have.  It appears the `markdown` package and a few others now support the syntax `[juicy](https://yummy.example.com){:target="_blank"}`, which would be one possible approach.

**Comment by nicholasserra** [comment]
Hey jeff, there's an extra called `target-blank-links` that adds the blank to every link output.

**Comment by JeffAbrahamson** [comment]
Thanks, Nicholas.  I think this doesn't quite hit my use case (which is a web app), because (1) it trusts incoming HTML, which on a web app I'm not too happy to do, and (2) it would appear to turn it on everywhere, not just for links specified by editors.

Have I missed something?

```
@register.filter(name='markdown')
def safe_markdown(value):
    """Safely render markdown to html.

    First escape any html so that we are sure the string is safe.

    Then render markdown to html so that we can render
    in a template as safe.

    Usage:

      {{ value|markdown }}
    """
    return mark_safe(markdown(escape(value), extras=["target-blank-links"]))

```

**Comment by nicholasserra** [comment]
Not sure what you mean with `trusts incoming HTML`, any html content coming into this library _should_ be escaped coming back out. Although we've had plenty of security fixes over the years, mostly blame to the nature of all the regex happening in the codebase.

I've been advocating for end users to also pass any output through a sanitizer like Bleach just to be safe.

Yes the extra turns on target blank globally, so if you want to do them individually that's not gonna work. This would require a new extra to be created. Other option is for you to hook into the preprocess and postprocess hooks and add your own functionality. It would require you to import and then extend the Markdown class in your own codebase.

https://github.com/trentm/python-markdown2/blob/master/lib/markdown2.py#L420-L432

**Comment by JeffAbrahamson** [comment]
> trusts incoming HTML

I may be entirely confused, as I'm usually a back-end guy, but I've understood that user-provided HTML is a security risk, and that this is one of the reasons we use markdown.  (That, and markdown is simpler and easier.)

> I've been advocating for end users to also pass any output through a sanitizer like Bleach just to be safe.

Bleach might be a better and more nuanced approach than just calling django's `escape`.  Thanks.

> if you want to do them individually that's not gonna work. This would require a new extra to be created. Other option is for you to hook into the preprocess and postprocess hooks and add your own functionality. It would require you to import and then extend the Markdown class in your own codebase.

My initial thought was to write a new extra.  It was not obvious to me that I could do that without it being accepted into the markdown2 library, which, in turn, ought reasonably to pass some threshold of general usability.  I'm not convinced my cases are important enough to others for that.

Subclassing and overriding preprocess and postprocess might be the right solution for me then.  Thanks!

**Comment by nicholasserra** [comment]
Right, so an end user could be providing you markdown, or they could be providing you malicious html, so this library tries to guard against that a bit by escaping or removing any unsafe html detected.

You're kind of in a weird situation since you're trying to pass the output from this library into a Django template. Normally, you'd leave the Django template to escape automatically. This is the default setting, any variable in a Django template is escaped on output.

But you want to show the rendered markdown, so you can't leave the markdown content escaped, or else the html won't work. So you're going to have to turn off escaping when outputting the markdown.

For anything you don't escape on output, you need to be sure it's safe. This library has had many XSS fixes, but I can't guarantee they're all caught. So if you're going to trust the output and render to the browser unescaped, you should probably also run through Bleach to sanitize, just as a double check.

**Comment by JeffAbrahamson** [comment]
For what it's worth, and partly just for info to far future browsers of this issue (if people browse closed issues), what I eventually did was to write a [small FSM](https://github.com/transport-nantes/tn_web/blob/master/transport_nantes/topicblog/tn_links.py) that implemented the syntax I wanted, then wrote [this](https://github.com/transport-nantes/tn_web/blob/master/transport_nantes/topicblog/templatetags/markdown.py) django templatetag:

```
@register.filter(name='markdown')
def safe_markdown(value):
    parser = TNLinkParser(verbose=True)
    return mark_safe(markdown(parser.transform(escape(value))))
```
