### ISSUE TITLE
How do I get access to the first title?

### ISSUE THREAD

**Issue by kevinrenskers** [trentm/python-markdown2#390]
Imagine this incredibly simple markdown file:

```
# Hello world
Foo bar.
```

When I use markdown2, I of course get a nice HTML string out of it, `<h1>Hello world</h1>\n\n<p>Foo bar.</p>\n`. But, is there any way I could get access to the first title? "Hello world" in this case. Of course I could make a regex that works on the `toc_html` attribute, but I was hoping for a better way 😅 

Then a second question, how hard would it be to split that markdown into 2 separate pieces: the title and then the rest of the document? So again with that simple document from above, the title would be "Hello world", but the output of the markdown parsing would only be `<p>Foo bar.</p>`.  The reason why I am asking this, is because I want to show metadata between the title and the body of the document, on my website. But because it's now one complete document, that's quite hard to do. I could fake it using paddings and margins but I'd rather no have to go that route.

**Comment by nicholasserra** [comment]
The output of this library isn't stored in any kind of structured fashion, it's all just processed and spit out. So you're better off preprocessing this beforehand, maybe stripping out the first title, then running the second half through markdown2, combining them after.

**Comment by kevinrenskers** [comment]
Thanks for the answer!
