### ISSUE TITLE
TOC not displayed when not in CLI

### ISSUE THREAD

**Issue by ant1j** [trentm/python-markdown2#397]
I am using this library and need the CLI in my generated HTML files.

It seems the TOC is only generated if it is used under the CLI mode:
https://github.com/trentm/python-markdown2/blob/65df9a25cda2c2b1e01d54ee932be96b8f097917/lib/markdown2.py#L404-L406

Disable the check seems to work fine.

Any reason why this condition is set?

Thanks

**Comment by nicholasserra** [comment]
Yeah it looks like we only prepend via CLI, or we attach to the output from the library via `toc_html` attr, but we don't by default include in the output text.

Not sure why, but PRs welcome on it if you have a clean way of implementing it in mind.

**Comment by JPHutchins** [comment]
This appears to be a bug IMO.  Can workaround like so:

```python
m = markdown2.Markdown(extras=EXTRAS)
m.cli = True
m.convert(markdown)
```
