### ISSUE TITLE
Way to access the AST

### ISSUE THREAD

**Issue by Arteneko** [trentm/python-markdown2#407]
For a project I'm working on, I'd like to access the AST of a markdown document.

Is there a way to access it in Markdown2?

**Comment by nicholasserra** [comment]
Can you be more specific? This library doesn't tokenize anything so there isn't really a tree that's stored that can be output. It's all regex on the fly.

**Comment by Arteneko** [comment]
I was trying to access a potential AST to be able to extract some meaningful metadata for my needs, but if there's no tokenization, this library will probably not fit my needs.
Thanks, anyways
