### ISSUE TITLE
Markdown metadata specification

### ISSUE THREAD

**Issue by Crozzers** [trentm/python-markdown2#423]
I was working on a fix for #398 and I noticed something about the `_meta_data_pattern` regexp. Here is the pattern for reference:
```regex
^(?:---[\ \t]*\n)?((?:[\S\w]+\s*:(?:\n+[ \t]+.*)+)|(?:.*:\s+>\n\s+[\S\s]+?)(?=\n\w+\s*:\s*\w+\n|\Z)|(?:\s*[\S\w]+\s*:(?! >)[ \t]*.*\n?))(?:---[\ \t]*\n)?
```
I noticed that throughout the regexp the definition a metadata key is inconsistent. For example, here are the definitions it allows:
* `[\S\w]+\s*:` = one or more non-whitespace or alphanumeric characters followed by optional whitespace before the colon
    * The `\w` seems redundant as alphanumeric characters are already non-whitespace
    * Does not allow for spaces in metadata keys
* `.*:` = zero or more non-newline characters
    * Allows for keys that contain nothing but whitespace
* `\w+\s*:` = one or more alphanumeric characters followed by an optional whitespace before the colon
    * Doesn't allow hyphens, whitespace or non-latin alphabet characters

There are also inconsistent definitions for what a metadata value can be:
* `.*` = zero or more non-newline characters
* `[\S\s]+` = one or more non-whitespace or whitespace characters
    * So literally anything goes including newlines?
* `\w+` = one or more alphanumeric characters

My question is: Is there a specification for what is allowed as metadata keys and values? I'm aware that this is an extra that is undefined by the [daring fireball markdown spec](https://daringfireball.net/projects/markdown/syntax) but is there a general community consensus?

The [Python-markdown definition](https://github.com/Python-Markdown/markdown/blob/383de86c64101b8d14768d9a247c9efc97d703bd/markdown/extensions/meta.py#L26) says that keys are one or more alphanumeric or hyphen chars and that values are zero or more non-newline characters.

[MultiMarkdown metadata](https://github.com/fletcher/MultiMarkdown/blob/ef1038d4812322550801e9f3a2fc45a403f2a656/bin/MultiMarkdown.pl#L1722) is the same except metadata keys cannot start with a hyphen or underscore and are allowed to contain spaces.

Both implementations seem to agree that metadata keys should be restricted to the latin alphabet whereas metadata values can be much more loosely defined. Is that something that makes sense to implement for this project? I would be happy to submit a PR.

**Comment by nicholasserra** [comment]
Thank you for taking a deep dive into this one. As far as a general community consensus: probably not. The extras in this package are kind of a free for all at this point. I think following one of the other packages probably makes sense.

The only point that struck me as odd is that MultiMarkdown is allowing spaces in the keys. That's odd to me. The python-markdown spec sounds a bit more sane. Wonder why multi-markdown is restricting leading hyphens. Maybe clashing with some other extra or addition.

Anyway, I think the python-markdown spec is mostly fine, so maybe a variation of that, that will pass tests here without much modification would be a good compromise. If you have some strong opinions let me know, but I think whatever you land on is probably fine, as long as it's mostly backwards compatible.

**Comment by Crozzers** [comment]
I'll probably end up with something like `\S+` for metadata keys and `.*` for values.
The only issues I'm having is with Python 2.7 testing where the markdown engine is producing unicode strings where the tests expect regular strings.
```
-  u'empty': '',
+  u'empty': u'',
```

**Comment by Crozzers** [comment]
Also, you mentioned that:
> The only point that struck me as odd is that MultiMarkdown is allowing spaces in the keys.

However in the current test suite, in [test/tm-cases/metadata.text](https://github.com/trentm/python-markdown2/blob/b912db0fd3251c28a09e905045d0c35a36220c1b/test/tm-cases/metadata.text#L7) and in [test/tm-cases/metadata2.text](https://github.com/trentm/python-markdown2/blob/b912db0fd3251c28a09e905045d0c35a36220c1b/test/tm-cases/metadata2.text#L6) there are in fact keys that contain spaces.
metadata.text has:
```
and some: >
 long value
   with complex indentation
 that goes multiline
```
And metadata2.text has:
```
another long: >
  long value
   with complex indentation
  that goes multiline
```

So perhaps keeping spaces in metadata keys is a good idea in case anyone has come to rely on this feature.
Maybe a regexp like `[\S \t]+` for metadata keys would fit the bill

**Comment by nicholasserra** [comment]
Yup that sounds fine to me then. I didn't realize we were depending on the spaces for tests.

**Comment by Crozzers** [comment]
After some thinking, `[\S \t]+` allows for completely empty (whitespace only) keys and might not be the best fit.
I suppose something like `[\S \t]*\S[\S \t]*`, where a non-whitespace character is required at some point in the string, would do but it seems a bit clunky and I'm not sure if there's a better way to do that.

As a sidenote: after doing some digging through the Python `re` docs it turns out that `\w` matches unicode word characters, so my earlier assumption about `\w` not allowing non-latin/non-ascii characters was wrong. However, in Python 2.7 it requires the `re.UNICODE` flag to work this way.

**Comment by nicholasserra** [comment]
We dropped 2.7 support on this repo, so if anything 2.7 is holding you up feel free to bail on it.
