### ISSUE TITLE
Improve error message if link_patterns forgotten

### ISSUE THREAD

**Issue by mangelozzi** [trentm/python-markdown2#428]
If one tries to use markdown2 as follows (in the case where one forgot to pass in `link_patterns` argument):

```python
content = markdown2.markdown( content, extras=["fenced-code-blocks", "tables", "link-patterns"])
```

It raises the error: `None type is not iterable`.

I guess `link_patterns` has a default value of `None`
If you would like it to work silently (maybe not good), then maybe default it to `(,)` or `[]`.

However if you prefer to be explicit, more pythonic I think, maybe you could add something like:
```python
assert link_patterns is not None, "If the 'link-patterns" extra is used, an argument for 'link_patterns' is required"
```

**Comment by nicholasserra** [comment]
Fixed in #430
