### ISSUE TITLE
H1 rendered as code block instead

### ISSUE THREAD

**Issue by mangelozzi** [trentm/python-markdown2#432]
`<h1>` style headings like this (the text `DJANGO WIDGETS` below):

```
# DJANGO WIDGETS

## FIELDS

- `field.html_name` (includes form prefix)
- `field.id_for_label`
- `field.value`
```

Are normally rendered as `<h1>` tags, e.g.:

# DJANGO WIDGETS

## FIELDS

- `field.html_name` (includes form prefix)
- `field.id_for_label`
- `field.value`

How markdown 2 renders them as code blocks:
```
<pre><code># DJANGO WIDGETS</code></pre>

<h2>FIELDS</h2>

<ul>
<li><code>field.html_name</code> (includes form prefix)</li>
<li><code>field.id_for_label</code></li>
<li><code>field.value</code></li>
</ul>
```

**Comment by Crozzers** [comment]
Hi there!

I tried your example on the latest git master branch and at tag 2.4.2 and could not reproduce the error.
Could you tell me what version of the library you are using, what Python version and any markdown extras that you might be using?

**Comment by mangelozzi** [comment]
> Hi there!
> 
> I tried your example on the latest git master branch and at tag 2.4.2 and could not reproduce the error. Could you tell me what version of the library you are using, what Python version and any markdown extras that you might be using?

Hi! 

Im using:
```
markdown2==2.4.2
Python 3.8.10
```

This is the code;

```py
import markdown2
content = self.nodelist.render(context)
html = markdown2.markdown( content, extras=["fenced-code-blocks", "tables"])
```

**Comment by mangelozzi** [comment]
This issue is due to django converting the html beforehand, the solution is to pass the html through a safe filter: `{{ content|safe }}`
