### ISSUE TITLE
Can't render a list, or single quote.

### ISSUE THREAD

**Issue by mangelozzi** [trentm/python-markdown2#433]
This mardown:
```
- `{% foo 'data1' %}`
- `{% foo 'data2' %}`
```

Should be rendered as:

- `{% foo 'data1' %}`
- `{% foo 'data2' %}`

However markdown2 renderes it as
```
<div class="markdown-body"><pre><code>- `{% foo &amp;#x27;data-form=&amp;quot;&amp;#x27;|add:gui|add:&amp;#x27; prefix&amp;quot;&amp;#x27; %}`
</code></pre>

<p>- <code>{% foo &amp;#x27;data-form=&amp;quot;office prefix&amp;#x27; %}</code></p>
</div>
```

Note a `'` (single quote) is rendered as `&amp;#x27;`, which is shown in a web browser as `&#x27`.

Was there posibily a release that broke the rendering? This together which the <h1> heading issue and other list issue I raised, it seems llike something must of happened to the rendering.

**Comment by Crozzers** [comment]
Hey there!

I was unable to reproduce this error using the latest master branch of the code or using release version 2.4.2.
Which markdown version are you using, which Python version, and are you using any markdown extras?

**Comment by mangelozzi** [comment]
> Hey there!
> 
> I was unable to reproduce this error using the latest master branch of the code or using release version 2.4.2. Which markdown version are you using, which Python version, and are you using any markdown extras?

> Hi there!
> 
> I tried your example on the latest git master branch and at tag 2.4.2 and could not reproduce the error. Could you tell me what version of the library you are using, what Python version and any markdown extras that you might be using?

Hi! 

Im using:
```
markdown2==2.4.2
Python 3.8.10
```

This is the code;

```py
import markdown2
content = self.nodelist.render(context)
html = markdown2.markdown( content, extras=["fenced-code-blocks", "tables"])
```

**Comment by mangelozzi** [comment]
This issue is due to django converting the html beforehand, the solution is to pass the html through a safe filter: `{{ content|safe }}`
