### ISSUE TITLE
Is it possible to convert relative .md links to .html links?

### ISSUE THREAD

**Issue by venthur** [trentm/python-markdown2#440]
Hi,

I'm trying to migrate from markdown to markdown2 for my [static site generator](https://github.com/venthur/blag). The migration worked quite well all extras I was using are supported here as well. The only thing that seems not to work is my custom `TreeProcessor` that converted **relative** markdown links to html, i.e. `[test](test.md)` becomes a link to `test.hml`.

The background is that I can write consistent markdown files with functioning markdown links between the documents but still generate valid html files. Is there a way to achieve that?

Not sure how familiar you are with the [python-markdown](https://github.com/Python-Markdown/markdown/) code base, but this is how I implemented the extension there:

```python
class MarkdownLinkTreeprocessor(Treeprocessor):
    """Converts relative links to .md files to .html

    """

    def run(self, root):
        for element in root.iter():
            if element.tag == 'a':
                url = element.get('href')
                converted = self.convert(url)
                element.set('href', converted)
        return root

    def convert(self, url):
        scheme, netloc, path, query, fragment = urlsplit(url)
        logger.debug(
            f'{url}: {scheme=} {netloc=} {path=} {query=} {fragment=}'
        )
        if (scheme or netloc or not path):
            return url
        if path.endswith('.md'):
            path = path[:-3] + '.html'

        url = urlunsplit((scheme, netloc, path, query, fragment))
        return url


class MarkdownLinkExtension(Extension):
    """markdown.extension that converts relative .md- to .html-links.

    """
    def extendMarkdown(self, md):
        md.treeprocessors.register(
                MarkdownLinkTreeprocessor(md), 'mdlink', 0,
        )
```

**Comment by nicholasserra** [comment]
We definitely don't have anything in here that converts .md links to .html. Would need a custom extra for that. But doesn't seem worth it for this one off case. Maybe try tapping in to the preprocess and postprocess methods to extract and handle them in your application?
