### ISSUE TITLE
Replace <strike> with <s> in strike extra

### ISSUE THREAD

**Issue by philgyford** [trentm/python-markdown2#444]
The `strike` extra turns `~~foo~~` into `<strike>foo</strike>` but that tag [is deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strike):

> Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the [compatibility table](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strike#browser_compatibility) at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.

The `<s>` tag appears to be the modern equivalent (with `<del>` only for specific cases) so should the `strike` extra use `<s>` instead?

**Comment by nicholasserra** [comment]
Yup looks like you're right, we should probably convert over to <s>
