### ISSUE TITLE
Underline and HTML comments

### ISSUE THREAD

**Issue by gitbra** [trentm/python-markdown2#450]
Hi team!

Underline and HTML comments are conflicting in some cases.
I share with you [this bug fix](https://github.com/trentm/python-markdown2/files/8885804/underline_html_comment.zip) that I am using in my wiki server.
I hope that you will find it interesting for your community of users.
Tell me if you have any comment: maybe is there any better way to achieve the same result?

Thanks & Happy weekend
Alex

**Comment by nicholasserra** [comment]
Hello Alex. Fix looks pretty simple, thank you. Could you open it up as a PR? Just easier for me.  If not I'll do it, just so I can let CI run tests on it.

**Comment by nicholasserra** [comment]
Tracking in #451
