### ISSUE TITLE
Is type stub provided?

### ISSUE THREAD

**Issue by mirumirumi** [trentm/python-markdown2#456]
I would be very happy to have a type stub file that can be handled by `mypy` etc.
Is it provided? If not, do you plan to consider it?

**Comment by nicholasserra** [comment]
Hello. We don't currently have one, and have no plans for it. But we wouldn't object to someone contributing one. Although would probably need some kind of enforcement via CI to make sure it's kept up to date. We get a lot of patches from one off people fixing things.

**Comment by mirumirumi** [comment]
Thanks for your response!
I got it, I would consider contributing as much as I can.
