### ISSUE TITLE
Add Support for tg-spoiler in extras

### ISSUE THREAD

**Issue by jk6521** [trentm/python-markdown2#476]
Support` || spoiler ||` -> ` <tg-spoiler>spoiler</tg-spoiler>`
Which is telegram spoiler syntax released recently

More info - https://core.telegram.org/bots/api#formatting-options

**Comment by nicholasserra** [comment]
Is this a telegram specific thing?  Or does the existing spoiler extra cover this?

https://github.com/trentm/python-markdown2/wiki/Extras

**Comment by jk6521** [comment]
What I'm mentioning is special to telegram only and spoilers which is already available in extra doesn't cover.

You can implement in two ways
- `<span class="tg-spoiler">spoiler</span>`, 
- `<tg-spoiler>spoiler</tg-spoiler>`

And I found 2nd way is the easiest one.

**Comment by jk6521** [comment]
Added PR #482 
Need approval of that

**Comment by nicholasserra** [comment]
Fixed in #482 482
