### ISSUE TITLE
Mixed ordered and unordered lists rendering as per spec?

### ISSUE THREAD

**Issue by Braintelligence** [trentm/python-markdown2#478]
Hello everyone!

When using ordered and unordered lists together strange behaviour is being observed. Strange in the sense that markdown parsers seem to interpret it differently.

I'm using easyMDE as a markdown editor and python-markdown2 for actual rendering.

But easyMDE interprets mixed lists differently than python-markdown2. See below.

**To Reproduce and Screenshots**
Use the following example content:
```
1. Test: 
Lorem Ipsum
- Lorem Ipsum
- Lorem Ipsum
- Lorem Ipsum
```

easyMDE Preview:
![image](https://user-images.githubusercontent.com/6761196/193810502-0b9cf55c-3a3a-4b73-98c6-14ba2ce6b126.png)
```
<ol>
<li>Test: 
Lorem Ipsum</li>
</ol>
<ul>
<li>Lorem Ipsum</li>
<li>Lorem Ipsum</li>
<li>Lorem Ipsum</li>
</ul>
```

python-markdown2 rendering (via django-markdown2):
![image](https://user-images.githubusercontent.com/6761196/193810566-66d0dd03-fac3-4921-936c-da8324fcb03e.png)
```
<ol>
<li>Test:<br>
Lorem Ipsum</li>
<li>Lorem Ipsum</li>
<li>Lorem Ipsum</li>
<li>Lorem Ipsum</li>
</ol>
```

**Expected behavior**
Not sure who is in the wrong here, but I'd expect it to render the same in the easyMDE preview and python-markdown2. If possible I'd want for easyMDE to preview the same behaviour that python-markdown2 is depicting.

If python-markdown2 is acting correctly I'd be happy if you could provide me to the specification which easyMDE is implementing the wrong way here.

Thanks a lot!

**Comment by Crozzers** [comment]
My gut instinct is to say that `python-markdown2` is behaving correctly here since it is accurately representing what you have put, which is a line break after your point.

This behaviour is not really clarified in the original daringfireball markdown spec, however, [babelmark seems to indicate](https://babelmark.github.io/?text=1.+Test%3A+%0ALorem+Ipsum%0A-+Lorem+Ipsum%0A-+Lorem+Ipsum%0A-+Lorem+Ipsum) that most implementations seem to lean towards the `easyMDE` way of doing it.
Commonmark also [produces the `easyMDE` result](https://spec.commonmark.org/dingus/?text=1.%20%20A%20paragraph%0Awith%20two%20lines.%0A*%20item%0A*%20item%0A*%20item%0A).

Perhaps for the sake of conformance, `python-markdown2` should also do this

**Comment by Braintelligence** [comment]
Thank you very much for your insight :).
In that case I hope that python-markdown2 will conform to this behaviour in the foreseeable future; that would be awesome.

**Comment by Crozzers** [comment]
Hang on a sec, I just tried this on the master branch d6651a4 and it produced the same output that `easyMDE` produced.
Are you using any markdown extras? Perhaps django is messing with the input?

**Comment by Braintelligence** [comment]
Just for the sake of completeness, I am indeed using some extras. These are: `safe, code-friendly, break-on-newline, strike, tables`

Thanks for checking!

**Comment by Crozzers** [comment]
Ok so the `break-on-newline` is the one that inserts the `<br>` tag.

And upon further reading, I completely mis-read the code snippet for the `python-markdown2` output. I focused on the `<br>` tag and completely missed how wrong that output is, so I apologise for that and I'm looking into it

**Comment by Braintelligence** [comment]
Hello everyone,

where can I find information about when the next release is to be expected so I can incorporate this fix into my project? :)

Thanks a lot!

**Comment by nicholasserra** [comment]
We don't have a set release schedule. I'll prioritize this one though. Once a few more fixes land i'll cut one and let you know.

**Comment by nicholasserra** [comment]
@Braintelligence 2.4.6 has been released
