### ISSUE TITLE
Incorrect code block conversion

### ISSUE THREAD

**Issue by XDanielPaul** [trentm/python-markdown2#489]
### Issue 
The code block

\`\`\` c
    const var = foo()
\`\`\`

is being converted to:

``` html
<pre><code>&lt;div class="codehilite"&gt;
&lt;pre&gt;&lt;span&gt;&lt;/span&gt;&lt;code&gt;&lt;span class="k"&gt;const&lt;/span&gt;&lt;span class="w"&gt; &lt;/span&gt;&lt;span class="n"&gt;var&lt;/span&gt;&lt;span class="w"&gt; &lt;/span&gt;&lt;span class="o"&gt;=&lt;/span&gt;&lt;span class="w"&gt; &lt;/span&gt;&lt;span class="n"&gt;foo&lt;/span&gt;&lt;span class="p"&gt;()&lt;/span&gt;&lt;span class="w"&gt;&lt;/span&gt;
&lt;/code&gt;&lt;/pre&gt;
&lt;/div&gt;
</code></pre>
```
and should be converted to:
``` html
<div class="codehilite">
    <pre><span></span><code><span class="k">const</span><span class="w"> </span><span class="n">var</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="n">foo</span><span class="p">()</span><span class="w"></span>
    </code></pre>
    </div>
```

### Observation
During the conversion, the input text passes through function `_do_code_blocks(self, text)` which hashes the `<div class="codehilite"></div>` and it's content and wraps them in `<pre><code></code></pre>`

Output of `_do_code_blocks(self, text)`:
``` html
'<pre><code>md5-353f226db77851404d4ad30e2cb646b8\n</code></pre>\n'
```

Output of `_do_code_blocks(self, text)` is passed as input through function `_unescape_special_chars(self, text)` and hash is converted to following output:
``` html
<pre><code>&lt;div class="codehilite"&gt;
&lt;pre&gt;&lt;span&gt;&lt;/span&gt;&lt;code&gt;&lt;span class="k"&gt;const&lt;/span&gt;&lt;span class="w"&gt; &lt;/span&gt;&lt;span class="n"&gt;var&lt;/span&gt;&lt;span class="w"&gt; &lt;/span&gt;&lt;span class="o"&gt;=&lt;/span&gt;&lt;span class="w"&gt; &lt;/span&gt;&lt;span class="n"&gt;foo&lt;/span&gt;&lt;span class="p"&gt;()&lt;/span&gt;&lt;span class="w"&gt;&lt;/span&gt;
&lt;/code&gt;&lt;/pre&gt;
&lt;/div&gt;
</code></pre>
```

### Steps to reproduce:
1. create markdown file and paste the text:
\`\`\` c
   const var = foo()
\`\`\`

2. python /lib/markdown2.py --extras fenced-code-blocks foo.md > foo.html

**Comment by Crozzers** [comment]
Hi there! I tried this and was unable to reproduce this issue. What version of the library are you using?

**Comment by XDanielPaul** [comment]
Hi @Crozzers! I have cloned the master branch, so I suppose I am using the most recent one

**Comment by Crozzers** [comment]
I can reproduce it if I indent the input like so:
````
    ``` c
    const var = foo()
    ```
````
Is that what is happening?

**Comment by XDanielPaul** [comment]
Also one more thing I found out, but I might create a separate issue if it's not correct behaviour:

````
Plain text
``` c
    const var = foo()
```
````

Gets converted to

``` html
<p>Plain text
    <div class="codehilite">
    <pre><span></span><code><span class="k">const</span><span class="w"> </span><span class="n">var</span><span class=">    </code></pre>
    </div></p>
```

Is the code block supposed to be wrapped in `<p></p>`?

**Comment by Crozzers** [comment]
I don't know about the `<p>` tags but I have a pretty good idea of why the codeblock is getting messed up.
It's probably detecting the indented code as a code block, not realizing it is inside a fenced code block. I'll look into a fix for that
