### ISSUE TITLE
Mermaid example is not working

### ISSUE THREAD

**Issue by falkoschindler** [trentm/python-markdown2#495]
I just copied the "full example" from https://github.com/trentm/python-markdown2/wiki/mermaid#full-example, ran it with Python3 and opened the resulting test-markdown.html. However, I don't see a rendered Mermaid graph, but only its source code:

```
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

Am I missing something?

It would be great to get Mermaid working with markdown2 so that we can integrate it into [NiceGUI](https://github.com/zauberzeug/nicegui).

**Comment by nicholasserra** [comment]
Is the javascript loading?

**Comment by falkoschindler** [comment]
@nicholasserra Yes, I think so.

But @SebastienDorgan over at https://github.com/zauberzeug/nicegui/discussions/277 found out that markdown2 "forgot to add the "mermaid" class to the code tag". And that the problem is already fixed on the main branch. So the fix might just not be released yet. I've tested with version 2.4.6.

**Comment by nicholasserra** [comment]
Oh, yup, good call. The feature isn't out yet. So either install against HEAD, or wait a bit and i'll try to push up a new release in the coming days.

**Comment by falkoschindler** [comment]
Great!
Since our package depends on markdown2, we'll wait for the PyPI release.

**Comment by nicholasserra** [comment]
2.4.7 has been released

https://pypi.org/project/markdown2/2.4.7/
