### ISSUE TITLE
someone help

### ISSUE THREAD

**Issue by sabuka-dumbo** [trentm/python-markdown2#503]
``my code:
```
def entry(request, entrys):
    markdowner = Markdown()
    bla = util.get_entry(entrys)
    return render(request, "encyclopedia/pages.html", {
        "entrys": entrys,
        "entrys_text": markdowner.convert(bla),
    })
```
and when im running it my http://127.0.0.1:8000/wiki/CSS page gave me this:
`<h1>CSS</h1> <p>CSS is a language that can be used to add style to an <a href="/wiki/HTML">HTML</a> page.</p>`

**Comment by Crozzers** [comment]
Hi there! This code sample doesn't really say anything about what the problem is. Could you attach an example of the markdown that is being processed here (eg: the value of the `bla` variable), along with a description of the issue and the expected behaviour.
