### ISSUE TITLE
Support block code

### ISSUE THREAD

**Issue by phongtnit** [trentm/python-markdown2#504]
Hi,

I tested markdown2 2.4.8 with block code in Markdown using "```". It is not supported.

For example:
```
>>> tup = (3, 2, 1)
>>> sorted_tup = sorted(tup)
>>> print(sorted_tup)
[1, 2, 3]

>>> sorted_tup_desc = sorted(tup, reverse=True)
>>> print(sorted_tup_desc)
[3, 2, 1]
```

The output is:
```
<p>```</p>

<blockquote>
  <blockquote>
    <blockquote>
      <p>tup = (3, 2, 1)
      sorted<em>tup = sorted(tup)
      print(sorted</em>tup)
      [1, 2, 3]</p>
    </blockquote>
  </blockquote>
</blockquote>
```

The desired output will look like:
```
<pre><code>
>>> tup = (3, 2, 1)
>>> sorted_tup = sorted(tup)
>>> print(sorted_tup)
[1, 2, 3]

>>> sorted_tup_desc = sorted(tup, reverse=True)
>>> print(sorted_tup_desc)
[3, 2, 1]
</code></pre>
```

Please check it, many thanks

**Comment by Crozzers** [comment]
Have you enabled the `fenced-code-blocks` extra? There's some documentation on the [extras wiki page](https://github.com/trentm/python-markdown2/wiki/Extras), along with an incomplete list of extras you can enable.

**Comment by phongtnit** [comment]
Thanks for your awesome help, that would fix my error.
