### ISSUE TITLE
Support for PyMDown Extensions

### ISSUE THREAD

**Issue by kjaymiller** [trentm/python-markdown2#507]
Is there support or planned support for<https://github.com/facelessuser/pymdown-extensions> or similar I understand that there may be issues with compatibility but it may also be easier than expected if the lexing and parsing are similar it may be eaiser than expected or potentially a fork could do it.

Starting my checks here in hopes it is already supported.

**Comment by Crozzers** [comment]
The short answer is that there is no support at the moment and no concrete plans.

I've been putting some thought into custom extras but haven't gotten very far with it. Main issue is seperating the current built-in extras from the main markdown parser. `fenced-code-blocks`, for example, is very deeply integrated with the code blocks support.

Regarding the format of the extensions, you can see the ideas I had in issue #382, however, re-inventing the wheel doesn't make a huge amount of sense and using an existing standard seems like a good idea

**Comment by kjaymiller** [comment]
Interesting enough I think I was looking for admonitions mostly and noticed they are supported - I didn't see them in the wiki.

**Comment by Crozzers** [comment]
Just added an [admonitions wiki page](https://github.com/trentm/python-markdown2/wiki/admonitions). Thanks for pointing that out
