### ISSUE TITLE
2.4.9 generates bad output for 'An [issue1](issue1) link'

### ISSUE THREAD

**Issue by rouilj** [trentm/python-markdown2#517]
Using python 3.6, 3.8, 3.10, 3.11 and 3.12 with 2.4.9 the string:

```
'An [issue1](issue1) link'
```
generates:
```
'<p>An <a href="#">issue1</a> link</p>\n'
```
when I expect:
```
'<p>An <a  rel="nofollow" href="issue1">issue1</a> link</p>\n'
```

This works as expected with 2.4.8 with my local changes.

I am subclassing Markdown2 to disable hyperlinks for some schemes:
```
_disable_url_schemes = ['javascript', 'data']
```
The code reads (from https://github.com/roundup-tracker/roundup/blob/master/roundup/cgi/templating.py#L59-L81):
```
def _import_markdown2():
    try:
        import markdown2
        import re

        class Markdown(markdown2.Markdown):
            # don't allow disabled protocols in links
            _safe_protocols = re.compile('(?!' + ':|'.join([
                re.escape(s) for s in _disable_url_schemes])
                                         + ':)', re.IGNORECASE)

        def _extras(config):
            extras = {'fenced-code-blocks': {}, 'nofollow': None}
            if config['MARKDOWN_BREAK_ON_NEWLINE']:
                extras['break-on-newline'] = True
            return extras

        markdown = lambda s, c: Markdown(safe_mode='escape', extras=_extras(c)).convert(s)  # noqa: E731
    except ImportError:
        markdown = None

    return markdown
```
When it is called in this test case, MARKDOWN_BREAK_ON is False and `_extras(c)` results in this call:
```
Markdown(safe_mode='escape', extras={'fenced-code-blocks': {}, 'nofollow': None}).convert('An [issue1](issue1) link')
```

I was able to reproducible it even without my shenanigans with this simple test:
```
>>> import markdown2
>>> markdown2.Markdown(safe_mode='escape', extras={'fenced-code-blocks': {}, 'nofollow': None}).convert('An [issue1](issue1) link')
'<p>An <a href="#">issue1</a> link</p>\n'
```
failure. This failed as well with 2.4.8 and only passed by going back to 2.3.3.

I saw couple of changes to link processing in the change notes:
* [pull #513] Fix relative links not working in safe mode (issue #254)

seems the most likely to cause this and also identified and early 2.3 release as working correctly.

**Comment by Crozzers** [comment]
Looks like #513 is where the issue was introduced. From a brief look, this happens because this isn't deemed a "safe" link and you're running in safe mode.
https://github.com/trentm/python-markdown2/blob/902353eeaac3ae2bc89b48a710b975ecb5b02248/lib/markdown2.py#L1634-L1638
Looks like relative URLs aren't deemed safe, although I'm not familiar with the reasoning why. The regex in question is pulled from Stack Exchange's [pagedown](https://github.com/StackExchange/pagedown/blob/32c0bdb121de04e0e956ddde0391022644ff1a76/Markdown.Sanitizer.js#L25C6-L25C7) repo so that may hold some clues.

I intend to give this a more thorough look soon

**Comment by rouilj** [comment]
> Looks like #513 is where the issue was introduced. From a brief look, this happens because this isn't deemed a
> "safe" link and you're running in safe mode.
>[...]
> I intend to give this a more thorough look soon

I updated my original report to indicate that my subclassed version (that overrides _safe_protocols) works with 2.4.8, but the simple test case fails with 2.4.8 as well s 2.4.9.

I agree that a relative link should be a safe link (or as safe as the page it's located on). Also when it fails, it doesn't add the `rel="nofollow"` attribute either.

**Comment by rouilj** [comment]
Also, from the regexp you posted, it looks like it is trying to do the job that _safe_protocols is supposed to do. Namely allowing/denying specific protocols. Using that regexp only allows http, https, ftp. If I say wanted to allow an ssh: protocol, there is no way to do it. Well I could subclass/overwrite _safe_href I guess.

**Comment by Crozzers** [comment]
Apologies for the delay but regarding the relative links, it looks like this was partially fixed in #513:
```markdown
[Allowed](#issue1)
[Allowed](/issue1)
[Allowed](./issue1)
[Not allowed](issue1)
```
So if you prefix all of your relative links with `./` then it should work.

> it is trying to do the job that _safe_protocols is supposed to do

#513 removed `_safe_protocols` in favour of the new `_safe_href` regex. Currently there is no way to extend the list of allowed protocols without overriding `_safe_href`.
I suppose we could add back a `_safe_protocols` property and do something like this:
```python
class Markdown:
    ...
    _safe_protocols = r'https?|ftp'
    @property
    def _safe_href(self):
        return re.compile(r'...%s...' % self_safe_protocols)
```

**Comment by rouilj** [comment]
Hello Crozzers:

> Apologies for the delay

No problem.

>but regarding the relative links, it looks like this was partially fixed in #513:
> 
> ```
> [Allowed](#issue1)
> [Allowed](/issue1)
> [Allowed](./issue1)
> [Not allowed](issue1)
> ```
> 
> So if you prefix all of your relative links with `./` then it should work.

Markdown2 is one of 3 (markdown, markdown2, mistune) optional markdown engines  
that can be used with the Roundup Issue Tracker. Part of standard Roundup is to change object  
references in plain text (e.g. issue23, user19) into links. Currently if markdown is enabled the Roundup Tracker core changes "`issue23`" into  
"`[issue23](issue23)`" and sends it off to the markdown engine for formatting. I suppose I can change the code to generate "`[issue23](./issue23)`" and see if the other  
markdown engines continue to do the right thing. But this is certainly not what I expected.
Also if a user wants to reference other items in the tracker (e.g. docs) they would need to know
about this trick.
 
Since Markdown has no formal spec, I am going to appeal to authority with:
github implemented it in 2013: <https://github.blog/2013-01-31-relative-links-in-markup-files/>
Since "`href="foo"` is a perfectly good relative link target setting, I would expect "`foo`" to work here as well.

> EDIT: `rel="nofollow"` is only added to links that have an href that doesn't start with `#`. (See Also 
[here](https://github.com/trentm/python-markdown2/blob/db75745320ca7747ae06dd4e5084977062a10379/lib/markdown2.py#L290)). This appears to be intentional

With that change, the href is set to "#" because it doesn't recognize "`[link](link)`" as a proper relative link. As a result the nofollow goes away. Got it.

Since this library is formatting user-generated content, at the very least "`rel="nofollow"`" is required. The other two engines are configured to use "`rel="nofollow noopener"`" and I have a ticket to extend that to include "ugc" in the relation. It would be nice to be able to do something similar with markdown2.

> > it is trying to do the job that _safe_protocols is supposed to do
> 
> #513 removed `_safe_protocols` in favour of the new `_safe_href` regex. Currently there is no way to extend the list of allowed protocols without overriding `_safe_href`. I suppose we could add back a `_safe_protocols` property and do something like this:
> 
> ```python
> class Markdown:
>     ...
>     _safe_protocols = r'https?|ftp'
>     @property
>     def _safe_href(self):
>         return re.compile(r'...%s...' % self_safe_protocols)
> ```

That would be helpful.

I have the yearly Roundup release occurring in a couple of weeks. In the installation notes, I have documented that markdown2 version 2.4.9 does not work and 2.3.3 is known to work. That's a good enough workaround for now.

**Comment by Crozzers** [comment]
> Since "href="foo" is a perfectly good relative link target setting, I would expect "foo" to work here as well.

I've submitted a PR (#520) to allow relative links in safe mode. I also added back the `_safe_protocols` attribute so you'll be able to extend it.

> The other two engines are configured to use "rel="nofollow noopener"" ... It would be nice to be able to do something similar with markdown2.

You can use the `target-blank-lines` extra but that also adds `target="_blank"` to the links.

**Comment by rouilj** [comment]
Hi Crozzers:

Thanks for #520.

`target-blank-lines` looks interesting, but opening the link in a new window might not be desirable.

However in looking at the extras, I might be able to use `link-patterns` to have markdown2 generate the `<a>` tags rather than preprocessing them into markdown format. However, that would be a markdown2 only thing and I am trying to keep my markdown processing pipeline generic.

Thanks for the feedback.

**Comment by nicholasserra** [comment]
@rouilj Can you test against 520 and make sure it's working as expected? PR looks good to me and i'll merge and release if so.

**Comment by rouilj** [comment]
> @rouilj Can you test against 520 and make sure it's working as expected? PR looks good to me and i'll merge and release if so.

Can you suggest how I do that? I install via pip. Would getting the diff via `https://..../520.patch | patch -r 1` in the directory where `markdown2.py` is installed work?

**Comment by nicholasserra** [comment]
@rouilj You can pip install a branch. You'll wanna use Crozzers branch here: https://github.com/Crozzers/python-markdown2/tree/fix-issue-517

Instructions:
https://stackoverflow.com/a/20101940

If you get hung up on this no worries, his PR looks to add a test case for this scenario. I just like to have extra confirmation. Thanks!

**Comment by rouilj** [comment]
@nicholasserra, the original failing test passed, but this test is now failing 8-):
```
        p = StringHTMLProperty(self.client, 'test', '1', None, 'test', u2s(u'An [issue1](https://example.com/issue1) link'))
>       self.assertIn( u2s(u'href="https://example.com/issue1"'), p.markdown().strip())
E       AssertionError: 'href="https://example.com/issue1"' not found in '<p>An <a href="#">issue1</a> link</p>'
```
the markdown input (p) is: `'An [issue1](https://example.com/issue1) link'`
markdown2 HTML output is: `'<p>An <a href="#">issue1</a> link</p>\n'`
so it looks like we just moved the error to the fully specified version 8-(.

I used:
```
python3 -m pip install -U  git+https://github.com/Crozzers/python-markdown2.git@fix-issue-517
```
to install the update. Running `python3 -c 'import markdown2; print(markdown2.__version__)'` returns `2.4.10`. So it looks like the install update was successful. I started with 2.4.8, pip updated to 2.4.9 an then to 2.4.10. The tests passed, failed, failed.

-- rouilj

**Comment by Crozzers** [comment]
Just tried this locally and it seemed to work just fine. Are the tests are being invoked with the same python install you used to install the feature branch? Any other extras or conditions that may be affecting it?

You may also need to adjust the way you override `_safe_protocols` since it's changed from a compiled regex to just a string in the PR branch. [Here's the diff](https://github.com/trentm/python-markdown2/pull/520/files#diff-59161098c0c2d506b5700112a54eb00354b867f46fa501a9f68cd86d843f1b57) if you want to take a look

**Comment by rouilj** [comment]
Hi @Crozzers:
> You may also need to adjust the way you override `_safe_protocols`
That was the trick. Once I changed it to:
```
  _safe_protocols = r'(?:https?):\/\/'
```
the tests passed.

I have to admit I am confused by the current definition of _safe_protocols (which I took to
be the same as matching allowed/safe schemas). Given that the original value is:
```
    _safe_protocols = r'(?:https?|ftp):\/\/|(?:mailto|tel):|\/|\.{,2}|#'
```
I did a little more testing as my change should have broken some use cases.
My understanding of the regexp alternations:
```
(?:https?|ftp):\/\/    - 1. look for http:// https:// ftp://
(?:mailto|tel):          - 2. look for mailto: or tel:
\/                           - 3. look for a leading / on the href
\.{,2}                      - 4. look for leading . or ..
#                           - 5. look for a fragment with leading #
```
With my new _safe_protocol setting, neither `[foo](/foo)` or `[foo](#foo)` should be processed
correctly. But the `/foo` case is processed properly while the `#foo` case is not. It sets `href="#"`.
This seems wrong as both should fail.  So #3 in my dissection of the original regexp is not right,
or is not needed because the leading / is allowed by something else in the final _safe_href pattern.

Also to me _safe_protocols seems to be misnamed given that it is looking for items 3, 4, and 5.
For example an href with a leading `#` inherits the protocol of the page and isn't a protocol on
its own.

Sadly the other three formatting engines (two markdown and reStructuredText) I support use a
blacklist to remove schemas. I think your whitelist is a better choice, but I will have some work
to do to convert my blacklist into a whitelist for use with markdown2 post 2.4.9.

==========
 
Also as an aside, I am getting a warning from a couple of other tests in my suite:
```
  markdown2.py:1366: FutureWarning: split() requires a non-empty pattern match.
    escape_seq, token = lead_escape_re.split(token)[1:] or ('', token)
```
I am not sure if this is new with 2.4.10 or not. My take on it is that token is sometimes
the empty string. The input to markdown2.convert() is '`<http://example.com/>`' and that
seems to trigger this warning.

Thanks for your efforts. Have a great day.

-- rouilj

**Comment by Crozzers** [comment]
> With my new _safe_protocol setting, neither `[foo](/foo)` or `[foo](#foo)` should be processed
correctly.

Yeah, currently `_safe_protocols` handles external and relative links all in one so extending it will require re-including the "local" link section

> Also to me _safe_protocols seems to be misnamed given that it is looking for items 3, 4, and 5.

I agree, the name is misleading. It ended up this way simply because of the range of links this is meant to cover. Trying to allow relative links in the same regex is a challenge. Might be easier to split the relative link detection into its own regex and combine it in some `is_href_safe` kind of function

**Comment by Crozzers** [comment]
> Might be easier to split the relative link detection into its own regex and combine it in some is_href_safe kind of function

I've added a commit to the PR that moves the handling of relative links out of `_safe_protocols` and into `_safe_href`. The new protocols regex looks like this:
```python
    _safe_protocols = r'(?:https?|ftp):\/\/|(?:mailto|tel):'
```
You should now be able to override `_safe_protocols` with just the protocols you want to allow and relative links should still be fine

**Comment by rouilj** [comment]
Hi Crozzers:

I just installed your latest changes.

When I set:
```
_safe_protocols = r'(?:https?):\/\/'
```
My results:

  * `[show](page)` case works fine.
  *  `(../page)` and `(./example`) cases works fine.
  * `(.../example`) case produces `href="#"` as desired.  Note Markdown and Mistune produce a link with `href=".../example". I am not sure that's a problem but it is different.
  * ` [baduser](mailto:baduser@daemons.com)` case produces `href="#"` as desired.

However, `A [phone](tel:0016175555555) link` case returns an `href="tel:0016175555555"`. I claim it should return `href="#"` right? Can you verify this test case fails?

**Comment by Crozzers** [comment]
> However, A `[phone](tel:0016175555555)` link case returns an `href="tel:0016175555555".` I claim it should return `href="#"` right?

Yep, fixed in the latest commit.
Accidentally had a `*` quantifier instead of `+` so in `example.com` it would only optionally match the `.com`, meaning that `tel:12345` looked like a "valid" domain with a port number.
Now is will require at least two levels on the domain name, eg: `example` and `.com`

**Comment by rouilj** [comment]
> > However, A `[phone](tel:0016175555555)` link case returns an `href="tel:0016175555555".` I claim it should return `href="#"` right?
> 
> Yep, fixed in the latest commit. It was matching against the protocol section in `_safe_href`. I added a negative lookbehind for `tel` so that shouldn't happen any more

Hmm, with:
```
  _safe_protocols = r'(?:https?):\/\/'
```
I claim `tel:` url's shouldn't be accepted. But in my test it looks like it is accepted. Am I missing something?

I ran:
```
python3 -m pip install -U  git+https://github.com/Crozzers/python-markdown2.git@fix-issue-517
```
to update to the newest version of your branch. I think it updated correctly and got your latest changes.

**Comment by Crozzers** [comment]
Is it on commit [6c8b1e7](https://github.com/trentm/python-markdown2/commit/6c8b1e7af3ee3c9df75d648bfb6a22aba7ea7a6b)?

Just re-tested it locally and it seems to be working fine

**Comment by rouilj** [comment]
Hmm:
```
$ python3 -m pip install -U  git+https://github.com/Crozzers/python-markdown2.git@fix-issue-517
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/Crozzers/python-markdown2.git@fix-issue-517
  Cloning https://github.com/Crozzers/python-markdown2.git (to revision fix-issue-517) to /tmp/pip-req-build-guu90bhj
  Running command git clone --filter=blob:none -q https://github.com/Crozzers/python-markdown2.git /tmp/pip-req-build-guu90bhj
  Running command git checkout -b fix-issue-517 --track origin/fix-issue-517
  Switched to a new branch 'fix-issue-517'
  Branch 'fix-issue-517' set up to track remote branch 'fix-issue-517' from 'origin'.
  Resolved https://github.com/Crozzers/python-markdown2.git to commit 6c8b1e7af3ee3c9df75d648bfb6a22aba7ea7a6b
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: markdown2
  Building wheel for markdown2 (setup.py) ... done
  Created wheel for markdown2: filename=markdown2-2.4.10-py2.py3-none-any.whl size=39332 sha256=ecbf0a5f6487e04034a7b473433c9742d87befa0071d36aa899d211ddd04ee25
  Stored in directory: /tmp/pip-ephem-wheel-cache-8dr71__a/wheels/88/8b/b5/d5a9af94c23d4256e83f6724f05ce1e23002d9dc772e01b4fb
Successfully built markdown2
Installing collected packages: markdown2
  Attempting uninstall: markdown2
    Found existing installation: markdown2 2.4.8
    Uninstalling markdown2-2.4.8:
      Successfully uninstalled markdown2-2.4.8
Successfully installed markdown2-2.4.10
```

The test now works. It must have have updated incorrectly in my last test.

I say ship it.

Thanks for your work to fix this.

-- rouilj

**Comment by nicholasserra** [comment]
Score, so everything seem to be resolved? If so i'll merge and ship that change to a fresh release

**Comment by rouilj** [comment]
It looks good to ship from the testing I have done. I think I covered all the cases.

**Comment by nicholasserra** [comment]
520 is now merged. I'll put this out as a new release within the next week.

**Comment by nicholasserra** [comment]
Thanks everyone!

**Comment by rouilj** [comment]
Thanks. I have my changes to Roundup ready support 2.4.8, 2.4.9 (it errors on startup) and 2.4.10.

**Comment by nicholasserra** [comment]
2.4.10 is now released on pypi
