### ISSUE TITLE
Bad handling of two consecutive bold words

### ISSUE THREAD

**Issue by m417z** [trentm/python-markdown2#541]
**Describe the bug**
See example below. 

**To Reproduce**
```markdown
**a** b **c**
```
Code:
```python
print(markdown2.markdown('**a** b **c**'))
```

**Expected behavior**
```html
<p><strong>a</strong> b <strong>c</strong></p>
```

Actual:
```html
<p><strong>a<em>* b *</em>c</strong></p>
```

**Debug info**
Version of library being used: 2.4.11

Any extras being used: None

**Additional context**

**Comment by fghaas** [comment]
I can confirm this; it appears to have slipped into the 2.4.11 release. 2.4.10 did not suffer from this issue. Downgrading to 2.4.10 is thus a valid temporary workaround.

**Comment by nicholasserra** [comment]
Thanks for the reports, we'll check this out

**Comment by Crozzers** [comment]
Hi, thanks for reporting this. I've opened a linked PR to address this, let me know if I've missed anything.

**Comment by gitbra** [comment]
Hi, thanks for the proposed fix.
I tested and the spaces inside `**` are not well appreciated, else it looks fine to me.

`**Word** **Word **`

`<p><strong>Word</strong> <em>*Word *</em></p>`

**Comment by Crozzers** [comment]
That is intentional and should match the behaviour of previous versions. From the [CommonMark spec](https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis):
> A [right-flanking delimiter run](https://spec.commonmark.org/0.30/#right-flanking-delimiter-run) is a [delimiter run](https://spec.commonmark.org/0.30/#delimiter-run) that is (1) not preceded by [Unicode whitespace](https://spec.commonmark.org/0.30/#unicode-whitespace), and...

**Comment by fghaas** [comment]
Thanks! I think you may still want to add an entry to the changelog for this fix — I've taken the liberty to submit a PR for that (see #553).
