### ISSUE TITLE
Markdown Syntax Not Converted Within HTML Tags in markdown2

### ISSUE THREAD

**Issue by syntaxsurge** [trentm/python-markdown2#546]
<h4 id="description">Description</h4>
<p>When using the <code>markdown2</code> library to convert Markdown to HTML, I&#39;ve noticed that Markdown syntax is not being converted inside HTML tags. Specifically, the bold syntax <code>**text**</code> within <code>&lt;p&gt;</code> tags is not converted to <code>&lt;strong&gt;</code> HTML tags as expected. This issue seems to affect Markdown syntax within any HTML tag, not just paragraph tags.</p>
<h4 id="steps-to-reproduce">Steps to Reproduce</h4>
<ol>
<li>Use the <code>markdown2</code> library to convert a string that contains both HTML and Markdown syntax. For example, a string with paragraph tags <code>&lt;p&gt;</code> containing Markdown bold syntax <code>**</code>.</li>
<li>Observe the output, where the Markdown syntax within the HTML tags is not converted.</li>
</ol>
<h4 id="expected-behavior">Expected Behavior</h4>
<p>Markdown syntax within HTML tags should be converted to their respective HTML tags. For example, <code>**text**</code> within <code>&lt;p&gt;</code> tags should become <code>&lt;p&gt;&lt;strong&gt;text&lt;/strong&gt;&lt;/p&gt;</code>.</p>
<h4 id="actual-behavior">Actual Behavior</h4>
<p>The Markdown syntax within HTML tags remains unchanged in the output HTML. For example, <code>**text**</code> within <code>&lt;p&gt;</code> tags stays as <code>&lt;p&gt;**text**&lt;/p&gt;</code>.</p>
<h4 id="environment">Environment</h4>
<ul>
<li>markdown2 version: 2.4.10</li>
<li>Python version: 3.10.12</li>
<li>Operating System: Linux Ubuntu</li>
</ul>
<h4 id="additional-information">Additional Information</h4>
<ul>
<li>This issue impacts the rendering of Markdown content in HTML environments where Markdown syntax is expected to be fully supported.</li>
<li>A temporary workaround involves manually processing the HTML to replace Markdown syntax with the corresponding HTML tags, but this is not ideal for a comprehensive Markdown processor like <code>markdown2</code>.</li>
</ul>
<h4 id="code-to-reproduce-optional-">Code to Reproduce</h4>
<pre><code class="lang-python"><span class="hljs-keyword">import</span> markdown2

input_text = <span class="hljs-string">'''
&lt;p&gt;Here is some bold text in Markdown: \*\*Bold Text\*\* within HTML tags.&lt;/p&gt;
'''</span>
output_html = markdown2.markdown(input_text, extras=[<span class="hljs-string">'tables'</span>, <span class="hljs-string">'footnotes'</span>])
print(output_html)  <span class="hljs-comment"># Expected: &lt;p&gt;Here is some bold text in Markdown: &lt;strong&gt;Bold Text&lt;/strong&gt; within HTML tags.&lt;/p&gt;</span>
                    <span class="hljs-comment"># Actual: &lt;p&gt;Here is some bold text in Markdown: **Bold Text** within HTML tags.&lt;/p&gt;</span>
</code></pre>

**Comment by Crozzers** [comment]
Have you tried the [`markdown-in-html`](https://github.com/trentm/python-markdown2/wiki/markdown-in-html) extra?

**Comment by syntaxsurge** [comment]
> Have you tried the [`markdown-in-html`](https://github.com/trentm/python-markdown2/wiki/markdown-in-html) extra?

Thank you for suggesting the markdown-in-html extra for markdown2. I tried using it as you recommended, but it appears that this feature doesn't support the specific nesting of Markdown within HTML tags in my case. In my content, the Markdown syntax (like **bold text**) is directly within <p> tags, which seems to prevent markdown2 from processing it correctly. The documentation for markdown-in-html indicates that the Markdown syntax should not be on the same line as the block-level HTML element, which is a constraint in my scenario as the string is constant and cannot be changed.

Do you have any other suggestions or workarounds that might help in this situation? Alternatively, are you aware of any other Markdown processors that might better handle this kind of nested Markdown within HTML? I appreciate your input and assistance on this.

**Comment by Crozzers** [comment]
> The documentation for `markdown-in-html` indicates that the Markdown syntax should not be on the same line as the block-level HTML element

My bad, I didn't realise that this limitation existed. I've opened a PR to address this. Let me know if that addresses the use case.
