### ISSUE TITLE
Update markdown2 version on PyPI

### ISSUE THREAD

**Issue by syntaxsurge** [trentm/python-markdown2#554]
Hello,

Is there any way to update the `markdown2` version on PyPI? I would prefer to use `pip install markdown2` in my Kubernetes configuration, rather than `pip install git+https://github.com/trentm/python-markdown2.git`.

The reason is that the latest pull request on GitHub addresses a critical aspect of my software, and it's important for me to have these updates. Thank you for your assistance.

**Comment by nicholasserra** [comment]
Which patch are you referring to?

We update the pypi version regularly, when enough fixes have landed. I'm planning on doing another release soon.

**Comment by nicholasserra** [comment]
2.4.12 has now been released, thanks!
