### ISSUE TITLE
Add typing to package

### ISSUE THREAD

**Issue by mar-pan** [trentm/python-markdown2#562]
When trying to lint code piece which is using your package with mypy it says that 
`module is installed, but missing library stubs or py.typed marker`

please add those it should be simple according to https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package/#adding-pytyped

**Comment by Crozzers** [comment]
There's a pending PR that drops Python 3.5, so if that goes through I'd be happy to add some inline type hints for the main user facing API

**Comment by mar-pan** [comment]
Hello how it's going

**Comment by Crozzers** [comment]
The PR I'm waiting on has received some updates and once it gets merged we can start adding type hints to the package
