### ISSUE TITLE
How to format task list

### ISSUE THREAD

**Issue by root3200** [trentm/python-markdown2#567]
Hello everyone.

I am using markdown 2 to upload the contents of a REAME.md using the confluence api which contains the following:

- [ ] incomplete task
- [ ] completed task

Tables and string formats like bold and strike work, but when trying to fomat the task list I get an error when running the script.

Is there any other way to use the extra task_list ?

example:

mardown2.Markdown(extras=['task_list'])

instead of:

markdown2.markdown(f"- [ ] task-1", extras=['task_list'])

you can see code script in my repositor

Thanks for your help

**Comment by Crozzers** [comment]
> you can see code script in my repositor

I assume you mean [this one](https://github.com/root3200/proyectos_python)?

I can't find any code where you're using the extra, and I wasn't able to reproduce the issue on my machine. Could you provide a sample input that demonstrates the error, and also tell us what the error is
